### PR TITLE
require db name when calling injectDbmQuery()

### LINKED ISSUE #2697: Service Name incorrectly encoded in DBM Trace Propagation
Hi.

We're trying out the new APM DBM Link for Postgres feature that got introduced in 3.9.0 (https://github.com/DataDog/dd-trace-js/pull/2480), but noticed that the Service Name isn't being correctly encoded when a Service Name function is used.

**Expected behaviour**
The injected DBM query comment resolves the service name and injects it correctly. Example:

```sql
/*dddbs='DUMMY',dde='development',ddps='backend',ddpv='1.0.0',traceparent='01-000000000000000064186e7c969771f2-4c44621c4eedd5ca-00'*/
```

**Actual behaviour**
The a serialized form of the function is rendered:

```sql
/*dddbs='(params)%20%3D%3E%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%22dummy%22.toUpperCase()%3B%0A%20%20%20%20%20%20%20%20%7D',dde='development',ddps='backend',ddpv='1.0.0',traceparent='01-000000000000000064186e7c969771f2-4c44621c4eedd5ca-00'*/
```

**Steps to reproduce**
Configure the Service Name for the `pg` plugin using a function (using a dummy function here for illustrative purposes):

```typescript
  tracer.use("pg", {
    service: (params: any) => {
      return "dummy".toUpperCase();
    },
  });
```

And then, enable DBM propagation using:

```typescript
    dbmPropagationMode: "full",
```

I've traced the issue down to [this line](https://github.com/DataDog/dd-trace-js/blob/v3.11.0/packages/dd-trace/src/plugins/database.js#L29), where the `this.config.service` property is being read directly, and not invoking the function. I don't think that the service name will be fully resolvable at the `DatabasePlugin` level, so it may need to be resolved directly in the PG plugin and passed as an argument to `injectDbmQuery` (happy to open a PR to fix this).

**Environment**

* **Operation system:** Linux
* **Node.js version:** 18.13.0
* **Tracer version:** 3.11.0
* **Agent version:** N/A
* **Relevant library versions:** `pg` @ 8.8.0

### PR DESCRIPTION
**Pull request by tlhunter**
### What does this PR do?

- database plugin provides database name to `injectDbmQuery()`
- database plugins can have dynamic names, cannot simply use `config.service` property

### Motivation

- fixes #2697

### CODE REVIEW

File: packages/datadog-plugin-pg/src/index.js [hunk 1]
```diff
@@ -9,6 +9,7 @@ class PGPlugin extends DatabasePlugin {
 
   start ({ params = {}, query, processId }) {
     const service = getServiceName(this.config, params)
```
Comment (tlhunter) [inline packages/datadog-plugin-pg/src/index.js:11]: This seems pretty weird to me.

Currently we take `this.config.service` and check if it's a function. If so we run the function with the connection as an argument. Otherwise we use the string value as is. The result is then used for the `startSpan()` code and then it is discarded.

Shouldn't we instead replace the `this.config.service` value with the evaluated version?

File: packages/datadog-plugin-mysql/src/index.js [hunk 2]
```diff
@@ -23,14 +23,15 @@ class MySQLPlugin extends DatabasePlugin {
       }
     })
   }
-}
 
-function getServiceName (config, dbConfig) {
-  if (typeof config.service === 'function') {
-    return config.service(dbConfig)
-  }
+  getServiceName (dbConfig) {
```
Comment (uurien) [inline packages/datadog-plugin-mysql/src/index.js:27]: It looks like it is the same implementation in mysql, oracledb and pg, can't we move this method to parent `DatabasePlugin` class?

**Comment by uurien** [comment]
Can we add some test to test the cache? checking that the method is only called once or something like that? If someone removes the cache, all test will continue working.

**Review by Qard — DISMISSED** [review]

**Comment by rochdev** [comment]
> Can we add some test to test the cache? checking that the method is only called once or something like that? If someone removes the cache, all test will continue working.

The functionality doesn't change so a test wouldn't really work here. Maybe a benchmark?

File: packages/datadog-plugin-mysql/src/index.js [hunk 3]
```diff
@@ -23,14 +23,15 @@ class MySQLPlugin extends DatabasePlugin {
...
+    if (typeof this.config.service === 'function') {
+      this.config.service = this.config.service(dbConfig)
```
Comment (rochdev) [inline packages/datadog-plugin-mysql/src/index.js:29]: This will not work because if you have 3 instances then all 3 will end up with the same service name. The whole point of the option is to dynamically return a different service name based on the configuration options.

**Review by rochdev — CHANGES_REQUESTED** [review]

File: packages/datadog-plugin-mysql/src/index.js (hunk 2 above)
Comment (tlhunter) [reply packages/datadog-plugin-mysql/src/index.js:27]: I really wanted to generalize it but the service name calculation was so different across implementations.

File: packages/datadog-plugin-mysql/src/index.js (hunk 3 above)
Comment (tlhunter) [reply packages/datadog-plugin-mysql/src/index.js]: Completely gutted the PR and removed all the caching stuff

**Review by uurien — APPROVED** [review]

**Review by rochdev — APPROVED** [review]

**Comment by tlhunter** [comment]
Squashed and rebased

**Review by Qard — APPROVED** [review]
