### PR TITLE
fix client sampling not reducing the tracer overhead

### LINKED ISSUE #543: sampleRate setting does not affect allocation
Shortly after a recent deployment we began seeing reduced throughput, increased latency and CPU spikes.

Tracing through afterwards it turns out the cause was an increase in the number of calls to datadog.trace(). The size of a given trace object went from 6kb to about 40kb. It was pretty difficult to see this though without turning on debug. I would not have expected the average engineer to be able to figure out what was going wrong.

The documentation seems to indicate that reducing the sample rate is a solution to load issues on servers with heavy load. However, tweaking the sample rate did not solve the throughput problem. Even setting to 0 or 0.01 still allocated new spans and new memory and triggered increased GC, behavior I was not expecting to see; I was expecting a decrease in the sample rate to decrease the number of objects being allocated.

### PR DESCRIPTION
**Pull request by rochdev**
This PR fixes client sampling not reducing the tracer overhead, or at least not enough.

Basically with the current implementation every span is still created, and tags are actually added and so on. The entire functionality is still there, but when the trace is finished, it's dropped instead of being formatted, encoded and flushed.

With this change, a shared no-op span is returned instead, so no additional allocation is done, and any operation on the span is ignored.

Fixes #543

### CODE REVIEW

File: src/opentracing/tracer.js [hunk 1]
```diff
@@ -65,6 +79,8 @@ class DatadogTracer extends Tracer {
   }
 
   _inject (spanContext, format, carrier) {
+    if (spanContext === this._noopSpan.context()) return this
```
Comment (rochdev) [inline src/opentracing/tracer.js]: @palazzem Should we propagate a sampling priority of `USER_REJECT` when the trace is dropped by client sampling, or should we simply not propagate any tracing information which will result in any other services called to be new root traces?
