### PR TITLE
fix express missing layer.stack and make all instrumentation safer

### LINKED ISSUE #1603: dd-trace-js overrides the default handle function/object on the Layer class in Express
**Describe the bug**
In our application, we load `dd-trace-js` as the first thing. On application boot, we also traverse through the express router stack for some more custom instrumentation. The reason we do that is to get a list of all registered endpoints. 

However, because dd-trace-js overrides/wraps the `handle` https://github.com/DataDog/dd-trace-js/blob/0f3983bf0c27a9d0ab0b2d2421a14860ce6fe08a/packages/datadog-plugin-router/src/index.js#L51, its no longer possible to read into `handle. stack` on a `Layer`. Instead as a workaround we need to read on `handle._datadog_orig.stack`

Following is an example of a Layer object

```javascript
Layer {
  handle: [Function: wrapCallHandle] {
    _datadog_orig: [Function: router] {
      params: {},
      _params: [],
      caseSensitive: undefined,
      mergeParams: undefined,
      strict: undefined,
      stack: [Array],
      _name: 'router'
    }
  },
  name: 'router',
  params: undefined,
  path: undefined,
  keys: [],
  regexp: /^\/?(?=\/|$)/i { fast_star: false, fast_slash: true },
  route: undefined,
  _datadog_matchers: [ { path: '/', test: [Function: test] } ]
}
```

What would be expected is to not have `_datadog_orig` represent the original handle function as a nested attribute. Example 

```javascript
Layer {
  handle: [Function: router] {
    params: {},
    _params: [],
    caseSensitive: undefined,
    mergeParams: undefined,
    strict: undefined,
    stack: [Array],
    _name: 'router'
  },
  name: 'router',
  params: undefined,
  path: undefined,
  keys: [],
  regexp: /^\/?(?=\/|$)/i { fast_star: false, fast_slash: true },
  route: undefined,
  _datadog_matchers: [ { path: '/', test: [Function: test] } ]
}
```

**Environment**

* **Operation system: Max OS 11.5.2**
* **Node version: 1v14.17.5**

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

* Replace the `shimmer` library with our own safer implementation that can handle methods but also functions.
* Replace most `original.call()` calls to `original.apply` to avoid missing arguments.
* Fix Express instrumentation breaking external usage of `layer.stack`.

### Motivation

Make instrumentation generally safer and fix #1603.

### CODE REVIEW

File: packages/datadog-shimmer/index.js [hunk 1]
```diff
@@ -0,0 +1,3 @@
+'use strict'
+
```
Comment (bengl) [inline packages/datadog-shimmer/index.js:2]: Files like this (i.e. just an immediate require-and-export) should be unnecessary. Is there any way we can avoid it? Maybe with a package.json or something?

File: packages/datadog-shimmer/src/shimmer.js [hunk 2]
```diff
@@ -0,0 +1,137 @@
...
+  if (!unwrapper) return target // target is already unwrapped or isn't wrapped
+
+  unwrapper()
+
+  return target
+}
+
+function massWrap (targets, names, wrapper) {
+  targets = [].concat(targets)
+  names = [].concat(names)
```
Comment (bengl) [inline packages/datadog-shimmer/src/shimmer.js:82]: We may have an opportunity here to impact startup performance by doing something like:

```js
function assertArray(maybeArray) {
  return Array.isArray(maybeArray) ? maybeArray : [maybeArray]
}
```

That way we avoid the unnecessary array creation and (usually quite expensive) `concat`. This might end up being a micro-optimization, but it could impact the startup-time benchmark.

File: packages/datadog-shimmer/src/shimmer.js [hunk 3]
```diff
@@ -0,0 +1,137 @@
...
+
+  for (const target of targets) {
+    for (const name of names) {
+      unwrap(target, name)
+    }
+  }
+}
+
+function assertMethod (target, name) {
+  if (!target) {
```
Comment (bengl) [inline packages/datadog-shimmer/src/shimmer.js:103]: Should types also be checked in these functions?

File: packages/datadog-shimmer/src/shimmer.js [hunk 4]
```diff
@@ -0,0 +1,137 @@
...
+    throw new Error('No function provided.')
+  }
+
+  if (typeof target !== 'function') {
+    throw new Error('Target is not a function.')
+  }
+}
+
+function assertNotClass (target) {
+  if (target.toString && target.toString().startsWith('class')) {
```
Comment (bengl) [inline packages/datadog-shimmer/src/shimmer.js:127]: I *think* `util.inspect` can differentiate these, so maybe there's a method on `util` or `util.types` that can help you here. It would be nice to do this without the `toString()` and `startsWith()`.

File: packages/datadog-shimmer/src/shimmer.js (hunk 2 above)
Comment (bengl) [reply packages/datadog-shimmer/src/shimmer.js:82]: Also, realistically, do we use _all_ the codepaths here? I.e. 1-target-1-name, n-target-n-name, 1-target-n-name, n-target-1-name? Maybe we can simplify here based on our actual usage (rather than just the existing shimmer API).

File: packages/datadog-shimmer/src/shimmer.js [hunk 5]
```diff
@@ -0,0 +1,137 @@
...
+  const props = Object.getOwnPropertyDescriptors(original)
+  const keys = Reflect.ownKeys(props)
+
+  for (const key of keys) {
+    Object.defineProperty(wrapped, key, props[key])
+  }
+}
+
+function wrapFn (original, delegate) {
+  assertFunction(delegate)
```
Comment (bengl) [inline packages/datadog-shimmer/src/shimmer.js:18]: To future-proof these a bit, can we have them return the value that's been checked?

e.g.

```js
delegate = assertFunction(delegate)
```

We'll need this later on to do type refinements (i.e. "narrowing").

**Review by bengl — CHANGES_REQUESTED** [review]

File: packages/datadog-shimmer/src/shimmer.js (hunk 2 above)
Comment (rochdev) [reply packages/datadog-shimmer/src/shimmer.js:82]: We do use all code paths. In my experience creating arrays and concatenating them is extremely cheap, so I doubt we'd really gain anything. Maybe I should add a benchmark?

File: packages/datadog-shimmer/index.js (hunk 1 above)
Comment (rochdev) [reply packages/datadog-shimmer/index.js:2]: It will no longer be needed when we switch to actual modules, but in the meantime I think this is cleaner than a random `package.json` that has no use.

File: packages/datadog-shimmer/src/shimmer.js (hunk 3 above)
Comment (rochdev) [reply packages/datadog-shimmer/src/shimmer.js:103]: Do types actually matter here? If yes we should focus only on the types that do.

File: packages/datadog-shimmer/src/shimmer.js (hunk 4 above)
Comment (rochdev) [reply packages/datadog-shimmer/src/shimmer.js:127]: `util.types` has nothing and the logic of `util.inspect` is extremely complicated and ends up ultimately doing exactly the same after it went through all the other checks.

File: packages/datadog-shimmer/src/shimmer.js (hunk 5 above)
Comment (rochdev) [reply packages/datadog-shimmer/src/shimmer.js:18]: Not sure I understand what you mean. If we'll need this later, should we just do it later?

Comment (bengl) [reply packages/datadog-shimmer/src/shimmer.js:18]: Yeah I guess it's an easy enough change to do later. Nevermind.

File: packages/datadog-shimmer/src/shimmer.js (hunk 3 above)
Comment (bengl) [reply packages/datadog-shimmer/src/shimmer.js:103]: Yeah, because non-object, non-function primitives can't have properties.

File: packages/datadog-shimmer/index.js (hunk 1 above)
Comment (bengl) [reply packages/datadog-shimmer/index.js:2]: I mean, this is an `index.js` that has no use. 😄 

Not gonna block on this.

File: packages/datadog-shimmer/src/shimmer.js (hunk 2 above)
Comment (bengl) [reply packages/datadog-shimmer/src/shimmer.js:82]: > In my experience creating arrays and concatenating them is extremely cheap, so I doubt we'd really gain anything.

In previous rounds of profiling, I've found them to be expensive. Right now it's (effectively) the same as previous code, so I'm fine with ignoring for now if you want to.

Comment (rochdev) [reply packages/datadog-shimmer/src/shimmer.js]: Not a big change anyway so I just did it 👍

File: packages/datadog-shimmer/src/shimmer.js (hunk 3 above)
Comment (rochdev) [reply packages/datadog-shimmer/src/shimmer.js:107]: Fixed.

**Review by bengl — APPROVED** [review]

**Review by bengl — APPROVED** [review]
