### PR TITLE
Fix Issue #620: pino plugin logs extra undefined values

### LINKED ISSUE #620: pino plugin logs extra undefined values
**Describe the bug**
The pino plugin is logging extra `undefined` values specifically for version 4 of pino.

For example, adding the following line to packages/datadog-plugin-pino/test/index.spec.js causes the test cases to fail only for pino version 4:
```javascript
expect(record).to.have.deep.property('msg', 'message')
```
Sample output:
```
  1) Plugin
       pino
         with pino 4 (4.0.0)
           with configuration
             should add the trace identifiers to logger instances:

      AssertionError: expected { Object (pid, hostname, ...) } to have deep property 'msg' of 'message', but got 'message undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined'
      + expected - actual

      -message undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined
      +message

  2) Plugin
       pino
         with pino 4 (4.17.6)
           with configuration
             should add the trace identifiers to logger instances:

      AssertionError: expected { Object (level, time, ...) } to have deep property 'msg' of 'message', but got 'message undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined'
      + expected - actual

      -message undefined undefined undefined undefined undefined undefined undefined undefined undefined undefined
      +message
```

### PR DESCRIPTION
**Pull request by esilkensen**
### What does this PR do?
The goal of this PR is to fix #620 - a minor bug with the pino plugin for pino v4.

The plugin defines a `logWithTrace(a, b, c, d, e, f, g, h, i, j, k)` function that wraps the `log` function returned by pino's [`genLog`](https://github.com/pinojs/pino/blob/v4.17.6/lib/tools.js#L61).

But if `logWithTrace` is only called with `a, b, c` (for example), the plugin calls `log` with the rest of those `e, f, g, h, i, j, k` values which logs them as `undefined`.

The pino implementation looks at `arguments.length` to decide how many values were passed in, and when it is called from `logWithTrace`, the `arguments` array contains values for all of `a, b, c, d, e, f, g, h, i, j, k` and logs them.

### Motivation
I'm using dd-trace-js with pino v4 and noticed it was logging lots of extra `undefined` values 🙂 

### Plugin Checklist
- [x] Unit tests.
- [x] CircleCI [jobs/workflows][4].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/src/plugins/index.js

### CODE REVIEW

File: packages/datadog-plugin-pino/src/index.js [hunk 1]
```diff
@@ -19,15 +19,21 @@ function createWrapGenLog (tracer, config) {
 
       return function logWithTrace (a, b, c, d, e, f, g, h, i, j, k) {
         const args = [a, b, c, d, e, f, g, h, i, j, k]
+        let argsLength = arguments.length
```
Comment (rochdev) [inline packages/datadog-plugin-pino/src/index.js]: Instead of keeping track of the length, would it be possible to use `args = [a, b, etc].slice(arguments.length)`? Then you would get a new array with the correct length upfront, so no need for the increment nor the loop.

Comment (esilkensen) [reply packages/datadog-plugin-pino/src/index.js]: That sounds good to me 👍

**Comment by esilkensen** [comment]
I think CI passed, but failed to update github for the checks listed as pending ("GitHub rate limited us while adding a commit status of success") - should they be retried?

**Comment by rochdev** [comment]
> I think CI passed, but failed to update github for the checks listed as pending ("GitHub rate limited us while adding a commit status of success") - should they be retried?

That's fine. It's a current limitation of CircleCI that we are working with them to address. In the meantime, the actual result of the build can be viewed directly on CircleCI.

**Comment by rochdev** [comment]
LGTM, thanks for the PR!
