### PR TITLE
[ci-app] Fix Mocha Instrumentation

### LINKED ISSUE #1222: Mocha plugin: "this.timeout is not a function"
**Describe the bug**
Hello,

I'm upgrading an app at work from `dd-trace` 0.26.1 to 0.30.2 in order [to resolve a vulnerability in the axios package](https://github.com/advisories/GHSA-4w2v-q235-vp99).  We use Mocha for our unit tests.  I noticed that a big diff adding specific Mocha support (https://github.com/DataDog/dd-trace-js/pull/1162) is included in that upgrade.

When we run our tests now, many tests fail to pass.  Specifically, any tests making use of [Mocha's `timeout` method](https://mochajs.org/#test-level) have started failing with a stacktrace looking like this:

```
     TypeError: this.timeout is not a function
      at /backend/transpiled/test/controllers/users.spec.js:18:1089
      at Context.<anonymous> (node_modules/dd-trace/packages/datadog-plugin-mocha/src/index.js:79:28)
      at /backend/node_modules/dd-trace/packages/dd-trace/src/tracer.js:94:56
      at /backend/node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:56
      at async_hooks.js:300:14
      at AsyncResource.runInAsyncScope (async_hooks.js:189:9)
      at AsyncLocalStorage.run (async_hooks.js:298:35)
      at Scope._activate (node_modules/dd-trace/packages/dd-trace/src/scope/async_local_storage.js:25:26)
      at Scope.activate (node_modules/dd-trace/packages/dd-trace/src/scope/base.js:12:19)
      at DatadogTracer.trace (node_modules/dd-trace/packages/dd-trace/src/tracer.js:45:35)
      at Context.<anonymous> (node_modules/dd-trace/packages/dd-trace/src/tracer.js:94:23)
      at Runner.runTestWithTrace [as runTest] (node_modules/dd-trace/packages/datadog-plugin-mocha/src/index.js:95:22)
```

Removing the tracer initialization code (`require('dd-trace').init(ddTraceOptions)`) from the app resolves the issue.

My hypothesis is that the above PR didn't include support for the `timeout` method.  

**Environment**

* **Operation system:**
* Debian buster, run as the `node:12-buster` docker image
* **Node version:**
* v12.20.1
* **Tracer version:**
* 0.30.2
* **Agent version:**
* N/A

### PR DESCRIPTION
**Pull request by juan-fernandez**
### What does this PR do?
* Fix bug where the spec function in `mocha` was not being called with the correct context. The fix is in https://github.com/DataDog/dd-trace-js/pull/1223/files#diff-3e917ea1366e30454d0aa44c11e64378545e1643def0c66baea963417518bc0dR66. 
* Add support for timeout errors (https://github.com/DataDog/dd-trace-js/pull/1223/files#diff-3e917ea1366e30454d0aa44c11e64378545e1643def0c66baea963417518bc0dR67-R71). These errors do not throw so we were not reporting them.
* Add tests. 

### Motivation
Fixed bug reported in https://github.com/DataDog/dd-trace-js/issues/1222

Fixes #1222 

### Plugin Checklist

- [x] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/dd-trace-js/blob/master/docs/API.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### CODE REVIEW

File: packages/datadog-plugin-mocha/src/index.js [hunk 1]
```diff
@@ -62,8 +63,12 @@ function createWrapRunTest (tracer, testEnvironmentMetadata, sourceRoot) {
           const activeSpan = tracer.scope().active()
           let result
           try {
-            result = await specFunction()
-            activeSpan.setTag(TEST_STATUS, 'pass')
+            result = await specFunction.call(context)
```
Comment (juan-fernandez) [inline packages/datadog-plugin-mocha/src/index.js:66]: I dropped the ball on this one. The spec function was not being called with the same context (for reference, how it is done in mocha: https://github.com/mochajs/mocha/blob/c667d1060f97da24abf48e41a284e037f0b410a0/lib/runnable.js#L366). Now it should be.

File: packages/datadog-plugin-mocha/src/index.js [hunk 2]
```diff
@@ -38,6 +38,7 @@ function createWrapRunTest (tracer, testEnvironmentMetadata, sourceRoot) {
   return function wrapRunTest (runTest) {
     return async function runTestWithTrace () {
       let specFunction = this.test.fn
+      const context = this.test.ctx
```
Comment (rochdev) [inline packages/datadog-plugin-mocha/src/index.js:41]: Is it expected that this is assigned before `this.test.fn`? Can `this.test.fn` be called only once? Otherwise wouldn't it be possible that it ends up with a previous context?

Comment (juan-fernandez) [reply packages/datadog-plugin-mocha/src/index.js:41]: the context is kept in retries:
https://github.com/mochajs/mocha/blob/master/lib/runner.js#L816-L824 https://github.com/mochajs/mocha/blob/c667d1060f97da24abf48e41a284e037f0b410a0/lib/test.js#L81, which I think should be the only time the spec function is called more than once

File: .circleci/config.yml [hunk 3]
```diff
@@ -627,6 +627,7 @@ jobs:
         environment:
           - SERVICES=mssql
           - PLUGINS=tedious
+          - DD_TRACE_DISABLED_PLUGINS=mocha
```
Comment (rochdev) [inline .circleci/config.yml:630]: This should not be needed. If it breaks for us it means it will break for others too.

**Review by rochdev — CHANGES_REQUESTED** [review]

File: .circleci/config.yml (hunk 3 above)
Comment (juan-fernandez) [reply .circleci/config.yml]: as spoken in Slack, I was testing whether `node-tedious` was testing because of the changes, but the errors are in other branches as well

File: packages/datadog-plugin-mocha/src/index.js (hunk 2 above)
Comment (juan-fernandez) [reply packages/datadog-plugin-mocha/src/index.js]: do you have any recommendation in mind? Or would we be good with this?

**Review by rochdev — APPROVED** [review]
