### PR TITLE
remove dependency on read-pkg-up

### LINKED ISSUE #1294: Vulnerability in sub-dependency hosted-git-info
**Describe the bug**
npm audit fails due to a vulnerability in:
dd-trace>read-pkg-up>read-pkg>normalize-package-data>hosted-git-info

https://github.com/npm/hosted-git-info/commit/bede0dc38e1785e732bf0a48ba6f81a4a908eba3
https://snyk.io/vuln/SNYK-JAVA-ORGWEBJARSNPM-1088356
https://snyk.io/vuln/SNYK-JS-HOSTEDGITINFO-1088355

Can be resolved by upgrading hosted-git-info to a version >= 3.0.8

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Remove dependency on `read-pkg-up`.

### Motivation

The `read-pkg-up` module has frequent breaking changes and recently dropped support for Node 8 which we still support for now.

Fixes #1294 #1319

### CODE REVIEW

File: packages/dd-trace/src/pkg.js [hunk 1]
```diff
@@ -1,17 +1,44 @@
...
 }
 
 function findPkg () {
   const cwd = findRoot()
-  const up = readPkgUp.sync({ cwd })
+  const filePath = findUp('package.json', cwd)
 
-  return up && up.pkg ? up.pkg : {}
+  try {
+    return readPkg(path.dirname(filePath))
```
Comment (Qard) [inline packages/dd-trace/src/pkg.js:17]: Why get the dirname if you're just going to convert it right back to the file path again in the function? Why not just have `readPkg` receive the complete file path?

Comment (rochdev) [reply packages/dd-trace/src/pkg.js]: Good catch, fixed.
