### PR TITLE
fix log injection not working when logger is required before dd-trace

### LINKED ISSUE #780: Log injection breaks when upgrading from v0.15.5 to v0.16.2
**Describe the bug**
When upgrading dd-trace to v0.16.2 logs do not contain dd (https://github.com/DataDog/dd-trace-js/blob/v0.16.2/packages/dd-trace/src/plugins/util/log.js#L13-L16) block any more.

The issue seems to be in `Instrumenter.enable` method https://github.com/DataDog/dd-trace-js/blob/v0.16.2/packages/dd-trace/src/instrumenter.js#L39-L52 Namely, plugins do not get auto-instrumented, because `this._enabled` is set to `true` after setting and loading the plugins and not before. `load` method simply returns if `this._enabled` is false: https://github.com/DataDog/dd-trace-js/blob/v0.16.2/packages/dd-trace/src/instrumenter.js#L98 Moving `this._enabled = true` to the begging of `enable` method fixes log injection issue, but might introduce others.

**Environment**
DD_LOGS_INJECTION=true
DD_TRACE_ANALYTICS_ENABLED=true
DD_RUNTIME_METRICS_ENABLED=true

* **Operation system:**
Alpine Linux 3.9.4
* **Node version:**
v10.17.0
* **Tracer version:**
v0.16.2
* **Agent version:**
v6.15.1

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix log injection not working when logger is required before `dd-trace`.

### Motivation

Fix #780

### CODE REVIEW

File: packages/dd-trace/src/instrumenter.js [hunk 1]
```diff
@@ -39,6 +39,8 @@ class Instrumenter {
   enable (config) {
     config = config || {}
 
+    this._enabled = true
```
Comment (brettlangdon) [inline packages/dd-trace/src/instrumenter.js]: why move this here?

Comment (rochdev) [reply packages/dd-trace/src/instrumenter.js]: Already loaded modules would not be tentatively patched otherwise (basically the next line).

Comment (brettlangdon) [reply packages/dd-trace/src/instrumenter.js]: so... maybe worth a comment on why we need to do it as soon as possible? ;)

Comment (rochdev) [reply packages/dd-trace/src/instrumenter.js]: It makes sense to start with this, since otherwise of course calling any other method might fail since it's not effectively enabled yet. The previous behavior is the one that would have needed an explanation, but it was wrong anyway.

Comment (brettlangdon) [reply packages/dd-trace/src/instrumenter.js]: and we have regression test for it.
