### PR TITLE
fix support for mongodb after mongodb-core merge

### LINKED ISSUE #697: Mongo traces no longer showing
**Describe the bug**

We recently upgraded some mongo dependencies:

```
FROM: 
    "mongodb": "^2.0.49",
    "mongoose": "^4.13.17",
    "mongoose-deep-populate": "^1.1.0",
TO:
    "mongodb": "^3.3.1",
    "mongoose": "^5.2.13",
    "mongoose-deep-populate": "^3.1.1",
```

Since that upgrade - mongo traces have stopped showing in APM.

~I am testing an upgrade to `dd-trace-js` in case that fixes the issue.~ No luck with the upgrade.

~Additionally I am in the process of testing the order in which dependecies are loaded to make sure `dd-trace-js` is still initialized first.~ It appears that dd-trace-js is still initialized before everything else.

**Environment**

* **Operation system:** Heroku Dyno
* **Node version:** 10.x
* **Tracer version:** 0.15.3
* **Agent version:** Heroku Buildpack

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix support for `mongodb` after `mongodb-core` merge.

### Motivation

Since `mongodb` 3.3, `mongodb-core` has been merged with `mongodb`, effectively changing the instrumented library name and the location of the internal modules.

Fixes #697

### CODE REVIEW

File: packages/datadog-plugin-mongodb-core/src/index.js [hunk 1]
```diff
@@ -76,7 +76,7 @@ function addHost (span, topology) {
 
 function wrapCallback (tracer, span, done, cursor) {
   return tracer.scope().bind((err, res) => {
-    if (err) {
+    if (err instanceof Error) {
```
Comment (brettlangdon) [inline packages/datadog-plugin-mongodb-core/src/index.js]: what else can it be?

Comment (rochdev) [reply packages/datadog-plugin-mongodb-core/src/index.js]: This change was made of another change that ended up not making it for this PR. Removed the check.
