### PR TITLE
[ci-visibility] Fix `CiPlugin` crashing when no CI Vis init is used

### LINKED ISSUE #2709: [Mocha] TypeError: this.tracer._exporter.getItrConfiguration is not a function
**Expected behaviour**
`dd-trace` should allow a Mocha test suite to run when using the standard `AgentExporter`

**Actual behaviour**
When trying to run a Mocha test suite, I get the following error:
```
TypeError: this.tracer._exporter.getItrConfiguration is not a function
    at /node_modules/dd-trace/packages/dd-trace/src/plugins/ci_plugin.js:19:29
    at Subscription._handler (/node_modules/dd-trace/packages/dd-trace/src/plugins/plugin.js:14:9)
    at Channel.publish (node:diagnostics_channel:56:9)
    at /node_modules/dd-trace/packages/datadog-instrumentations/src/mocha.js:351:26
    at exports.AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at Mocha.run (/node_modules/dd-trace/packages/datadog-instrumentations/src/mocha.js:350:27)
``` 

**Steps to reproduce**

As far as I can tell, here is what seems to be happening:

The Exporter for the `tracer` is being set to `AgentExporter` when `config.experimental.exporter` is not provided:
https://github.com/DataDog/dd-trace-js/blob/a96389bc5de239da74769f6fb8cfdfbcefb8e386/packages/dd-trace/src/opentracing/tracer.js#L23

https://github.com/DataDog/dd-trace-js/blob/a96389bc5de239da74769f6fb8cfdfbcefb8e386/packages/dd-trace/src/exporter.js#L25

ITR Configuration Channel is set up here:
https://github.com/DataDog/dd-trace-js/blob/a96389bc5de239da74769f6fb8cfdfbcefb8e386/packages/datadog-instrumentations/src/mocha.js#L20

Event is published to that channel here, when Mocha starts:
https://github.com/DataDog/dd-trace-js/blob/a96389bc5de239da74769f6fb8cfdfbcefb8e386/packages/datadog-instrumentations/src/mocha.js#L358

Published event is handled is called here:
https://github.com/DataDog/dd-trace-js/blob/a96389bc5de239da74769f6fb8cfdfbcefb8e386/packages/dd-trace/src/plugins/ci_plugin.js#L19

Handler fails because the `_exporter` (`AgentExporter`) on the tracer was never set up with a `getItrConfiguration` function.

**Environment**

* **Operation system:** Mac
* **Node.js version:** 16.17.0
* **Tracer version:** 3.11.0
* **Agent version:** N/A
* **Relevant library versions:** mocha@6.1.4

### PR DESCRIPTION
**Pull request by juan-fernandez**
### What does this PR do?
When the tracer is initialised without using ci visibility (`ci/init`) and a ci vis plugin is used, such as a `mocha`, the plugin has the invalid assumption that `getItrConfiguration` is available in the exporter. 

This PR fixes that. 

### Motivation
Fix #2709

### CODE REVIEW

File: packages/dd-trace/src/plugins/ci_plugin.js [hunk 1]
```diff
@@ -16,6 +16,9 @@ module.exports = class CiPlugin extends Plugin {
     super(...args)
 
     this.addSub(`ci:${this.constructor.name}:itr-configuration`, ({ onDone }) => {
+      if (!this.tracer._exporter.getItrConfiguration) {
```
Comment (uurien) [inline packages/dd-trace/src/plugins/ci_plugin.js:19]: It looks like `NoopTracer` does not initialize the `this._exporter`, shouldn't be necessary to check `tracer._exporter` as well?
```suggestion
      if (!this.tracer._exporter || !this.tracer._exporter.getItrConfiguration) {
```

Comment (juan-fernandez) [reply packages/dd-trace/src/plugins/ci_plugin.js:19]: yeah good catch

**Review by uurien — APPROVED** [review]
