### PR TITLE
fix instrumented functions missing symbols from the original

### LINKED ISSUE #1120: DNS tracing fail
**Describe the bug**
When tracing DNS, all dns.lookup call will fail 

**Environment**

* **Operation system:** macOS catalina, Kubernetes 1.16
* **Node version:** 14.13.1
* **Tracer version:** 0.26.1
* **Agent version:** 

## Repro

https://github.com/bodinsamuel/dd-trace-dns-issue

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix instrumented functions missing symbols from the original.

### Motivation

Fix #1120. It's not the first time that there is a symbol missing on a shim from a plugin, so I did the fix directly on `Instrumenter`. This makes `wrap` significantly slower, but it should only be called when patching so that should't be an issue.

There might be the same issue in some cases for non-symbol properties, but that may have more implications so for now I preferred to focus only on symbols, especially given their prominence in Node core.

### CODE REVIEW

File: packages/dd-trace/src/instrumenter.js [hunk 1]
```diff
@@ -115,7 +115,19 @@ class Instrumenter {
       })
     })
 
-    shimmer.massWrap.call(this, nodules, names, wrapper)
+    shimmer.massWrap.call(this, nodules, names, function (original, name) {
```
Comment (bengl) [inline packages/dd-trace/src/instrumenter.js:118]: Can you add a comment referencing https://github.com/othiym23/shimmer/issues/19 so that we know why we did this?

Comment (rochdev) [reply packages/dd-trace/src/instrumenter.js:118]: Sure, but it's not necessarily a bug since the library doesn't copy anything from the function, so it could be intended.

**Review by bengl — APPROVED** [review]
