### PR TITLE
fix: Lambda handler must be awaited

### LINKED ISSUE #2893: Lambda errors are always wrapped as `Runtime.UnhandledPromiseRejection`
It seems the latest 2.x versions of the dd-trace does not propagate the original error thrown by lambda function.

We observed this behaviour after upgrading to `2.27.1` from `2.24.0`. 

The error is preserved when running with `2.24.0`. We are not sure yet which version exactly broke this behaviour.

**Expected behaviour**
_(refer to the sample lambda below)_
```
ERROR	[dd.trace_id=** dd.span_id=**] Invoke Error 	
{
    "errorType": "CustomError",
    "errorMessage": "my error",
    "stack": [
        "CustomError: my error",
        "    at <stack trace redacted for clarity>..."
    ]
}
```

However, the following is observed.
**Actual behaviour**
_(refer to the sample lambda below)_
```
[dd.trace_id=** dd.span_id=**] Unhandled Promise Rejection 	
{
    "errorType": "Runtime.UnhandledPromiseRejection",
    "errorMessage": "CustomError: my error",
    "reason": {
        "errorType": "CustomError",
        "errorMessage": "my error",
        "stack": [
            "CustomError: my error",
            "    at <stack trace redacted for clarity>..."
        ]
    },
    "promise": {},
    "stack": [
        "Runtime.UnhandledPromiseRejection: CustomError: my error",
        "    at process.<anonymous> (file:///var/runtime/index.mjs:1189:17)",
        "    at process.emit (node:events:513:28)",
        "    at process.emit (/var/task/node_modules/source-map-support/source-map-support.js:516:21)",
        "    at emit (node:internal/process/promises:140:20)",
        "    at processPromiseRejections (node:internal/process/promises:274:27)",
        "    at processTicksAndRejections (node:internal/process/task_queues:97:32)"
    ]
}
```

**Steps to reproduce**
Sample lambda handler code to reproduce the above scenario.
```ts
class CustomError extends Error {
  constructor(message?: string) {
    super(message)
    Object.defineProperty(this, 'name', { value: 'CustomError' })
  }
}

export function myHanlder() {
  throw new CustomError('my error')
}
```

**Environment**

* **Operation system:** amazon/aws-lambda-nodejs:16.2023.03.08.12
* **Node.js version:** 16.x
* **Tracer version:** 2.27.1
* **Agent version:** latest (`datadog/lambda-extension:latest`)
* **Relevant library versions:**
  * **datadog-lambda-js:** 6.87.0

### PR DESCRIPTION
**Pull request by astuyve**
### What does this PR do?
Fixes #2893 

### Motivation
With this change, errors are thrown and escalated properly:
image

without this change, handler errors become unhandled promise rejections:
image

### Plugin Checklist
TODO - add units

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### CODE REVIEW

File: packages/dd-trace/src/lambda/handler.js [hunk 1]
```diff
@@ -83,21 +83,9 @@ function extractContext (args) {
...
-        // clear the timeout as soon as a result is returned
-        patched.then(_ => clearTimeout(__lambdaTimeout))
-      }
-    } catch (e) {
-      log.debug('Error patching AWS Lambda handler. Timeout spans will not be generated.')
-    }
-
-    return patched
+    checkTimeout(context)
+    return lambdaHandler.apply(this, args).then((res) => { clearTimeout(__lambdaTimeout); return res })
```
Comment (duncanista) [inline packages/dd-trace/src/lambda/handler.js:89]: shouldn't we catch in case an error gets thrown from our side? for debug purposes?

**Review by duncanista — APPROVED** [review]
lgtm, nice catch AJ! :shipit:

File: packages/dd-trace/src/lambda/handler.js (hunk 1 above)
Comment (astuyve) [reply packages/dd-trace/src/lambda/handler.js:89]: `apply` in this case calls the handler method, so error handling is already performed by the lambda runtime. Anything we'd do would just log and re-throw the error anyway, so I'm not sure we need anything additional here.

**Review by rochdev — APPROVED** [review]
