### PR TITLE
fix fs errors when using promisified methods

### LINKED ISSUE #983: Using `dd-trace` in `express` app with `@prisma/client` leads to exception `true`
## Bug Description

I have a `express` app that uses `@prisma/client` for database access. As soon as I add `dd-trace` (the datadog instrumentation library / tracer) to the app, the database query throws an exception `true` with no further information (Datadog Agent can be running or not - does not matter).

Reproduction repository: https://github.com/janpio/prisma-express-datadog-exception (Clone, run `npm install`, then `node index.js` to start the Express server. Confirm working by opening `localhost:5000/ok`.)

---

When I run `node index.js` and then request `localhost:5000/crash` this is shown in the console:

```
C:\Users\Jan\Documents\prisma-express-datadog-exception>node index.js
Listening on 5000 (possibly http://localhost:5000 )
exception  true
```

---

As the database connection string is invalid, I expect and error message like this from Prisma Client:

```
C:\Users\Jan\Documents\prisma-express-datadog-exception>node index.js
Listening on 5000 (possibly http://localhost:5000 )
exception  PrismaClientKnownRequestError: 
Invalid `prisma.customer.findMany()` invocation in
C:\Users\Jan\Documents\prisma-express-datadog-exception\index.js:15:47


  Can't reach database server at `localhost`:`5432`

Please make sure your database server is running at `localhost`:`5432`.
    at PrismaClientFetcher.request (C:\Users\Jan\Documents\prisma-express-datadog-exception\node_modules\@prisma\client\runtime\index.js:1:149082)
    at processTicksAndRejections (internal/process/task_queues.js:85:5) {
  code: 'P1001',
  meta: { database_host: 'localhost', database_port: 5432 }
}
```

I can switch between the expected and the buggy behavior by uncommenting the first line `const tracer = require('dd-trace').init();` in my `index.js`.

Seems like the usage of `dd-trace` leads to Prisma Client crashing in a bad way.

Any ideas?

## Environment

* **Operation system:** Windows or Heroku
* **Node version:** 12.6.0
* **Tracer version:** 0.21.1
* **Agent version:** - / 7.20.1

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix `fs` errors when using promisified methods.

### Motivation

Node uses symbols internally to store alternative implementations for some `fs` methods. The tracer wrapped these methods without copying the symbols, causing errors to be thrown when the promisified version was used.

Fixes #983

### CODE REVIEW

File: packages/datadog-plugin-fs/src/index.js [hunk 1]
```diff
@@ -356,6 +362,17 @@ function makeFSTags (resourceName, path, options, config, tracer) {
   return tags
 }
 
+function copySymbols (from, to) {
+  const props = Object.getOwnPropertyDescriptors(from)
+  const keys = Reflect.ownKeys(props)
+
+  for (const key of keys) {
```
Comment (bengl) [inline packages/datadog-plugin-fs/src/index.js:369]: https://npm.im/copying

**Comment by janpio** [comment]
Thanks @rochdev!
