### PR TITLE
[esbuild] add esbuild.js to npm package, change warning message

### LINKED ISSUE #2983: `dd-trace/esbuild` is missing on npm
**Expected behaviour**

https://www.npmjs.com/package/dd-trace/v/3.17.0?activeTab=code lists `esbuild.js`

**Actual behaviour**

It doesn't.

**Steps to reproduce**

Just visit the URL.

**Environment**

Doesn't matter.

### PR DESCRIPTION
**Pull request by tlhunter**
### What does this PR do?
- change the node.js version range warnings when attempting to bundle via esbuild
- actually includes esbuild.js in npm package (a la `require('dd-trace/esbuild')`)
- fixes #2983

### Motivation
- otherwise it doesn't work
- also users won't get warnings for all incompatible scenarios
- make the warning range match the README

### CODE REVIEW

File: packages/datadog-esbuild/index.js [hunk 1]
```diff
@@ -93,11 +93,18 @@ module.exports.setup = function (build) {
   })
 }
 
+// Currently esbuild support requires Node.js >=v16.17 or >=v18.7
+// Better yet it would support Node >=v14.17 or >=v16
+// Of course, the most ideal would be to support all versions of Node that dd-trace supports.
+// Version constraints based on Node's diagnostics_channel support
```
Comment (rochdev) [inline packages/datadog-esbuild/index.js:99]: Why is that an issue only for this feature but not for other things using DC?

Comment (tlhunter) [reply packages/datadog-esbuild/index.js:99]: I don't know. Haven't had a chance to look into it yet. Fixing the core issue is my next task.

**Review by Qard — APPROVED** [review]
