### PR TITLE
Fix Pino instrumentation

### LINKED ISSUE #1328: DD trace does not inject with pino prettyPrint
Without prettyPrint activated, dd traces are injected correctly. When I activate prettyPrint, the dd traces are no longer showing up.

**Environment**

* **Logger:**
* pino
* **Operation system:**
* Mac OSX  
* **Node version:**
* v12.21
* **Tracer version:**
* v0.20.0
* **Agent version:**

### PR DESCRIPTION
**Pull request by simon-id**
### What does this PR do?
- [x] Change the instrumentation for pino>=5.14.0 for futur proofing (use `mixin` function instead of `asJson`)
- [x] Add instrumentation for pinno-pretty (fixes #1328)

### Plugin Checklist
- [x] Unit tests.

### CODE REVIEW

File: packages/datadog-plugin-pino/src/index.js [hunk 1]
```diff
@@ -2,17 +2,16 @@
 
 const { LOG } = require('../../../ext/formats')
 
-function createWrapPino (tracer, config) {
+function createWrapPino (tracer, config, symbol, wrapper) {
```
Comment (simon-id) [inline packages/datadog-plugin-pino/src/index.js:5]: Not sure this is how you guys usually pass params to `createWrap...()`, I couldn't find an example to replicate. So if there is a "standard" way to do it, let me know.

File: packages/dd-trace/src/plugins/index.js [hunk 2]
```diff
@@ -38,6 +38,7 @@ module.exports = {
   'paperplane': require('../../../datadog-plugin-paperplane/src'),
   'pg': require('../../../datadog-plugin-pg/src'),
   'pino': require('../../../datadog-plugin-pino/src'),
+  'pino-pretty': require('../../../datadog-plugin-pino-pretty/src'),
```
Comment (simon-id) [inline packages/dd-trace/src/plugins/index.js:41]: Do you think we should have pino-pretty be standalone or directly inside the pino plugin ?

Comment (bengl) [reply packages/dd-trace/src/plugins/index.js:41]: I think it should be inside the pino plugin. I don't feel strongly about this though. @rochdev ?

Comment (rochdev) [reply packages/dd-trace/src/plugins/index.js:41]: I agree. The idea for plugins is that is does what a user would expect when enabled. When enabling the `pino` plugin, I would expect `pino` to just work without having to explicitly enable individual formatters etc, so in that sense it makes more sense to have a single plugin.

File: packages/datadog-plugin-pino/src/index.js (hunk 1 above)
Comment (rochdev) [reply packages/datadog-plugin-pino/src/index.js:5]: Yes, that is generally how additional params are passed. There isn't a standard per se however, this pattern is used a lot mostly because it's convenient when wrapping but it's not mandatory.

File: packages/dd-trace/src/plugins/index.js (hunk 2 above)
Comment (simon-id) [reply packages/dd-trace/src/plugins/index.js:41]: Alright, make sense, I'll merge it back to the pino plugin.

File: packages/datadog-plugin-pino/src/index.js (hunk 1 above)
Comment (simon-id) [reply packages/datadog-plugin-pino/src/index.js:5]: Ok, thanks for the precision!

File: packages/dd-trace/test/plugins/externals.json [hunk 3]
```diff
@@ -86,5 +86,11 @@
       "name": "pg-native",
       "versions": ["3.0.0"]
     }
+  ],
+  "pino": [
```
Comment (rochdev) [inline packages/dd-trace/test/plugins/externals.json:90]: This is not needed since there is an actual integration for `pino-pretty` now, which will cause it to already be installed.

**Review by rochdev — CHANGES_REQUESTED** [review]

File: packages/dd-trace/test/plugins/externals.json (hunk 3 above)
Comment (simon-id) [reply packages/dd-trace/test/plugins/externals.json:90]: I tried on a fresh repo to remove this and run the test with `yarn && PLUGINS=pino yarn test:plugins:ci` and it's failing the tests because it's missing `pino-pretty`. Either I'm missing a preliminary command, or it's the fact that `pino` itself is requiring the module (not our tests' code) that makes it not detect the automatically installed `pino-pretty` version. What do you think ?

Comment (rochdev) [reply packages/dd-trace/test/plugins/externals.json:90]: It should definitely work even without. There might be a different reason why the test is failing.

File: packages/datadog-plugin-pino/test/index.spec.js [hunk 4]
```diff
@@ -53,6 +54,25 @@ describe('Plugin', () => {
             expect(record).to.have.deep.property('msg', 'message')
           })
         })
+
+        if (!semver.intersects(version, '>=4.10.0 <=5.0.0-rc.1')) {
```
Comment (rochdev) [inline packages/datadog-plugin-pino/test/index.spec.js:58]: Why these versions specifically? What is different in that range?

Comment (simon-id) [reply packages/datadog-plugin-pino/test/index.spec.js:58]: In this small range (4.10.0 - 4.19 + 5.0.0-rc.1), there is a check in pino itself that goes `if (prettyPrint && outputStream !== process.stdout) throw`. So it makes it tedious to test anything as I'd have to mess with the global stdout. Do you think it's worth instrumenting the global `process.stdout` in the unit tests just for that ?

Comment (rochdev) [reply packages/datadog-plugin-pino/test/index.spec.js:58]: Yeah, it's easy enough to stub/unstub it with Sinon that I think it's worth making sure that the test versions match the support range.

**Comment by Mo33n** [comment]
Hi @rochdev, @simon-id,

Is there any workaround?
Any idea when this can be released?

**Comment by simon-id** [comment]
@Mo33n Can't think of an easy workaround no, as `pino-pretty` is not really flexible on its internals.
I was planning on finishing this PR this week, although I can't say about a release as I'm not in charge of that.

**Comment by Mo33n** [comment]
That's Great @simon-id, Could you please tag someone who can help with the release part?

**Comment by rochdev** [comment]
@Mo33n That would be me! I can make a release as soon as this is merged if you need it urgently.

**Review by rochdev — APPROVED** [review]

**Comment by Mo33n** [comment]
Thanks, @simon-id  and @rochdev, You guys are champs.
