### PR TITLE
fix address tag for dns lookups with `all` option

### LINKED ISSUE #2026: Bad serialization of DNS address in dns.lookup traces
**Expected behaviour**
`dns.address` field in traces should be readable.

**Actual behaviour**
`dns.address` field in traces is serialized as [object Objec],[object Object]

image

**Steps to reproduce**

I'm guessing that this line here https://github.com/DataDog/dd-trace-js/blob/master/packages/datadog-plugin-dns/src/index.js#L47 needs to deal with serializing the output.

Looking at the documentation for `dns.lookup` in node [docs](https://nodejs.org/dist/latest-v16.x/docs/api/dns.html#dnslookuphostname-options-callback) we have these examples, where we can see that the result might be an array of objects.

> With the all option set to true, the arguments for callback change to (err, addresses), with addresses being an array of objects with the properties address and family.

```node
const dns = require('node:dns');
const options = {
  family: 6,
  hints: dns.ADDRCONFIG | dns.V4MAPPED,
};
dns.lookup('example.com', options, (err, address, family) =>
  console.log('address: %j family: IPv%s', address, family));
// address: "2606:2800:220:1:248:1893:25c8:1946" family: IPv6

// When options.all is true, the result will be an Array.
options.all = true;
dns.lookup('example.com', options, (err, addresses) =>
  console.log('addresses: %j', addresses));
// addresses: [{"address":"2606:2800:220:1:248:1893:25c8:1946","family":6}]
```

We use @grpc/grpc-js (v 1.6.7) which has the following code https://github.com/grpc/grpc-node/blob/422e8cbcba42b13a00614707cca308b2a08220de/packages/grpc-js/src/resolver-dns.ts#L195
```js
this.pendingLookupPromise = dnsLookupPromise(hostname, { all: true });
```
As can be seen the `options.all = true` applies here and would give us the array of objects result as specified in the `dns.lookup` docs, unfortunately its not part of the type documentation, only as a side effect of passing `options.all = true` 😅 

**Environment**

* **Operation system: Bottlerocket (kubernetes nodes)**
* **Node.js version:**  Node v14
* **Tracer version:**  dd-trace 1.7.0
* **Agent version:**  gcr.io/datadoghq/agent:7.32.4
* **Relevant library versions:**  dd-trace 1.7.0,  @grpc/grpc-js (v 1.6.7)

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix address tag for dns lookups with `all` option.

### Motivation

The tag is otherwise set to an array of `[Object object]`.

Fixes #2026

### CODE REVIEW

**Review by bengl — APPROVED** [review]

File: packages/datadog-plugin-dns/src/index.js [hunk 1]
```diff
@@ -44,7 +44,8 @@ class DNSPlugin extends Plugin {
       this.enter(span, store)
     }, (result) => {
       const { span } = storage.getStore()
-      span.setTag('dns.address', result)
+      const address = Array.isArray(result) ? result[0].address : result
+      span.setTag('dns.address', address)
```
Comment (Flydiverny) [inline packages/datadog-plugin-dns/src/index.js:48]: If I'm reading this right, would it not be better in the case of an array to do something like `result.map((r) => r.address).join(', ')` to ensure all resolved addresses are listed?
Maybe a bit misleading if you expect `dns.address` to include 1 ip, but I think now its misleading in another way saying a DNS only resolved 1 address when in fact it would have resolved to several of them?

Comment (rochdev) [reply packages/datadog-plugin-dns/src/index.js:48]: The default behaviour without `all` is to take the first one, so I went with the same approach to keep a single address. I'm not sure what makes the most sense since I'm not sure what the point of the option is in the first place and in what scenario the first one is not what would be used 😅 Do you know why `grpc` uses the `all` option?

Comment (Flydiverny) [reply packages/datadog-plugin-dns/src/index.js:48]: We for various reasons use client side load balancing on our gRPC setup, so I believe that gRPC uses the all option to resolve all the potential IPs for the domain so it can do round robin on the IPs it resolved.
But this is a guesstimate from my side 😄 

Yesterday we had these traces during an incident 
image

As can be seen it performs a dns lookup and then proceeds to try to connect to each of the 3 resolved IPs (or at least I assume those IPs would match what the dns lookup resulted in)

Comment (rochdev) [reply packages/datadog-plugin-dns/src/index.js:48]: How do you use the tag? Would it make more sense to split the address as multiple tags or comma-separated is fine? I wonder if it should go under a different name too.

Comment (Flydiverny) [reply packages/datadog-plugin-dns/src/index.js:48]: Human observation 😄 the automatic dns instrumentation has helped us in a few cases when reading traces.
I think either solution would be fine, in the case of an array putting it under `addresses` as a comma separated list could make sense.
