### PR TITLE
fix consumer span not waiting for message ack before finishing

### LINKED ISSUE #964: GCP pubsub trace not measuring actual message handling time
**Describe the bug**

We use Datadog to trace GCP Pubsubs message publish and consume. 
Pubsub message consumption is an async process that ends when `msg.ack()` is called. I expect Datadog to messure the time from message receive to the call of msg.ack. 

The actual behavior is that pubsub.receive  calls are traced to be very (microseconds) short and do not include all async operations up to ack

**Environment**
Production

* **Operation system:**
Ubuntu

* **Node version:**
12

* **Tracer version:**
0.20.2

* **Agent version:**

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix consumer span not waiting for message ack before finishing.

### Motivation

A message has only been handled after it has been acknowledged. The library handles messages that are not acknowledged in time with a deadline system so it's guaranteed that the message will eventually be acknowledged even if there is a bug in the user code that never calls ack/nack.

Closes #964

### CODE REVIEW

File: packages/datadog-plugin-google-cloud-pubsub/src/index.js [hunk 1]
```diff
@@ -40,23 +40,65 @@ function createWrapRequest (tracer, config) {
...
-      if (eventName !== 'message' || !message) {
+      if (eventName !== 'message' || !message || !message._datadog_span) {
         return emit.apply(this, arguments)
       }
 
-      const topic = this.metadata && this.metadata.topic
+      const span = message._datadog_span
+
+      return tracer.scope().activate(span, () => {
+        try {
```
Comment (bengl) [inline packages/datadog-plugin-google-cloud-pubsub/src/index.js:50]: Why would emit throw?

Comment (rochdev) [reply packages/datadog-plugin-google-cloud-pubsub/src/index.js:50]: If one of the listener throws, we need to capture that error. However, it should re-throw which is not the case right now, so I'll fix that.

**Review by bengl — APPROVED** [review]
