### PR TITLE
fix sampling priority applied incorrectly

### LINKED ISSUE #1234: MANUAL_DROP does not appear to work
**Describe the bug**

I'm attempting to use a hook in Datadog's GraphQL instrumentation to completely ignore some traces.  According to the [online documentation](https://docs.datadoghq.com/tracing/faq/trace_sampling_and_storage/#manually-control-trace-priority), I should be able to call `span.setTag(tags.MANUAL_DROP)`.

However, this does not appear to work in practice.  

Sample code:

```ts
tracer.use('graphql', {
  hooks: {
    execute: (span, args, res) => {
      if (shouldIgnore(res)) {
        span?.setTag(MANUAL_DROP, true);
      }
    },
  },
});
```

Stepping through with a debugger, it appears that [we only consider](https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/span_processor.js#L14-L27) the priority sampler for the final span in a trace, and even then, that doesn't actually appear to modify the value of `_traceFlags.sampled`.  The trace shows up in the APM web UI simply with a `manual.drop: true` tag attached:

Screen Shot 2021-02-04 at 11 56 05 AM

Is there some other way that I should be filtering noisy requests out of APM?

**Environment**

* **Operating system:** MacOS 11.2
* **Node version:** 14.15.4
* **Tracer version:** 0.30.5
* **Agent version:** N/A

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix sampling priority applied incorrectly.

- Priority tags were ignored when sampling was applied on a different span. Sampling now happens every time a tag is added on every span to be able to persist the priority as soon as it's set.
- Metrics were added to whatever was the current span instead of on the root. They are now correctly added only on the root of the distributed trace at the same time the the priority is actually set instead of in the exporter.
- ~The sampling priority decision is now added only to the local root instead of to all spans when exporting.~

### Motivation

There were a few issues leading to inconsistencies with how sampling priority is applied and its corresponding metrics are reported.

Fixes #1234

### CODE REVIEW

File: packages/dd-trace/src/format.js [hunk 1]
```diff
@@ -91,7 +89,6 @@ function extractTags (trace, span) {
     addTag(trace.meta, trace.metrics, 'language', 'javascript')
   }
 
-  addTag(trace.meta, trace.metrics, SAMPLING_PRIORITY_KEY, priority)
   addTag(trace.meta, trace.metrics, ORIGIN_KEY, origin)
```
Comment (brettlangdon) [inline packages/dd-trace/src/format.js:92]: Do we need the same change here as well on origin? only set it on the local root span?

> You must set the _dd.origin tag on the local root trace with the value from the X-Datadog-Origin header.

Comment (rochdev) [reply packages/dd-trace/src/format.js:92]: I'll revert this change instead as we don't have a good way to handle the concept of a local root right now and it would require pretty much a rewrite of the exporter.

File: packages/dd-trace/src/format.js [hunk 2]
```diff
@@ -96,6 +100,18 @@ function extractTags (trace, span) {
   addTag(trace.meta, trace.metrics, HOSTNAME_KEY, hostname)
 }
 
+function extractRootTags (trace, span) {
+  const context = span.context()
+  const isLocalRoot = span === context._trace.started[0]
+  const parentId = context._parentId
+
+  if (!isLocalRoot || (parentId && parentId.toString(10) !== '0')) return
```
Comment (bengl) [inline packages/dd-trace/src/format.js:108]: Rather than doing a `toString`, can we not do a comparison w/ a/the zero id?

**Review by bengl — CHANGES_REQUESTED** [review]

File: packages/dd-trace/src/format.js (hunk 2 above)
Comment (rochdev) [reply packages/dd-trace/src/format.js:108]: No because it's not used in all cases.

**Review by bengl — APPROVED** [review]

**Review by brettlangdon — APPROVED** [review]
