### PR TITLE
fix possible app crash in latest when used with meteor 2.0

### LINKED ISSUE #1229: dd-trace causes crash in v8 internals, SIGABRT
**Describe the bug**

After upgrading to node 12.20.1, we are getting the below crash on our localhost consistently. `DD_TRACE_ENABLED=false` resolves the issue, so it looks like `dd-trace` is implicated. 

```
W20210201-11:27:47.096(-8)? (STDERR) program[53589]: ../src/api/callback.cc:123:void node::InternalCallbackScope::Close(): Assertion `(env_->execution_async_id()) == (0)' failed.
W20210201-11:27:47.097(-8)? (STDERR)  1: 0x1011f62d5 node::Abort() (.cold.1) [program]
W20210201-11:27:47.098(-8)? (STDERR)  2: 0x1000a5a29 node::Abort() [program]
W20210201-11:27:47.098(-8)? (STDERR)  3: 0x1000a5891 node::Assert(node::AssertionInfo const&) [program]
W20210201-11:27:47.099(-8)? (STDERR)  4: 0x100001c96 node::InternalCallbackScope::Close() [program]
W20210201-11:27:47.099(-8)? (STDERR)  5: 0x10000223a node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [program]
W20210201-11:27:47.100(-8)? (STDERR)  6: 0x100016598 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [program]
W20210201-11:27:47.100(-8)? (STDERR)  7: 0x10015d560 node::StreamBase::CallJSOnreadMethod(long, v8::Local<v8::ArrayBuffer>, unsigned long, node::StreamBase::StreamBaseJSChecks) [program]
W20210201-11:27:47.101(-8)? (STDERR)  8: 0x10015f2d1 node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [program]
W20210201-11:27:47.102(-8)? (STDERR)  9: 0x1000c3224 node::(anonymous namespace)::Parser::OnStreamRead(long, uv_buf_t const&) [program]
W20210201-11:27:47.103(-8)? (STDERR) 10: 0x100163d6f node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [program]
W20210201-11:27:47.105(-8)? (STDERR) 11: 0x100975355 uv__stream_io [program]
W20210201-11:27:47.107(-8)? (STDERR) 12: 0x10097deac uv__io_poll [program]
W20210201-11:27:47.109(-8)? (STDERR) 13: 0x10096a651 uv_run [program]
W20210201-11:27:47.110(-8)? (STDERR) 14: 0x1000e8d97 node::NodeMainInstance::Run() [program]
W20210201-11:27:47.111(-8)? (STDERR) 15: 0x10007b0e9 node::Start(int, char**) [program]
W20210201-11:27:47.112(-8)? (STDERR) 16: 0x7fff6b74bcc9 start [/usr/lib/system/libdyld.dylib]
=> Exited from signal: SIGABRT
=> Your application is crashing. Waiting for file change.
```

**Environment**

localhost development

* **Operation system:**

OS X 10.15.7

* **Node version:**

12.20.1

* **Tracer version:**

0.30.5

* **Agent version:**

N/A, running on my localhost

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix possible app crash in latest when used with Meteor 2.0 by updating the tracer to default to the `async_resource` scope manager since the issue seems to be a bug in `AsyncLocalStorage`.

### Motivation

Applications using Meteor 2.0 with the tracer are experiencing random C++ errors. While it's still unclear why this is happening, switching to the `executionAsyncResource` based scope manager seems to resolve the issue.

Fixes #1229

### CODE REVIEW

File: packages/dd-trace/src/platform/node/index.js [hunk 1]
```diff
@@ -42,10 +42,10 @@ const platform = {
   off: emitter.removeListener.bind(emitter),
   Loader,
   getScope (scope) {
-    if (scope === scopes.ASYNC_RESOURCE) {
-      return require('../../scope/async_resource')
-    } else if (scope === scopes.ASYNC_LOCAL_STORAGE || (!scope && hasSupportedAsyncLocalStorage)) {
+    if (scope === scopes.ASYNC_LOCAL_STORAGE) {
       return require('../../scope/async_local_storage')
+    } else if (scope === scopes.ASYNC_RESOURCE || (!scope && hasSupportedAsyncLocalStorage)) {
```
Comment (bengl) [inline packages/dd-trace/src/platform/node/index.js:47]: This line seems wrong, now that you've swapped them? In particular, `hasSupportedAsyncLocalStorage`.

**Review by bengl — CHANGES_REQUESTED** [review]

**Review by bengl — APPROVED** [review]
Lgtm

**Comment by schmod** [comment]
Any clue if this was a performance regression, or if there are plans to restore `AsyncLocalStorage` as the default scope-manager?

**Comment by rochdev** [comment]
@schmod The new scope manager basically does the same thing that `AsyncLocalStorage` itself does under the hood, and simply removes any additional logic that we don't need, some of which resulted in an incompatibility with `fibers` which Meteor uses. Because of that, it would be extremely unlikely to be slower than `AsyncLocalStorage` since it's basically a subset of the same code.
