### PR TITLE
Fix startuplog crashing by serializing bigint

### LINKED ISSUE #5829: [BUG]: TypeError: Do not know how to serialize a BigInt
### Tracer Version(s)

5.54.0

### Node.js Version(s)

20x

### Bug Report

after upgrading app crashes like such:
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at Object.toString (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/startup-log.js:64:19)
    at startupLog (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/startup-log.js:46:42)
    at /usr/src/app/node_modules/dd-trace/packages/dd-trace/src/exporters/agent/writer.js:98:7
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/dd-trace/packages/dd-trace/src/exporters/common/request.js:93:11)
    at IncomingMessage.emit (node:events:536:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

### Reproduction Code

_No response_

### Error Logs

_No response_

### Tracer Config

_No response_

### Operating System

_No response_

### Bundling

Unsure

### PR DESCRIPTION
**Pull request by BridgeAR**
Instead, handle bigint and symbols in the future.
Also make the bigint which caused it private and use a getter for
tests instead.

Fixes #5829

### CODE REVIEW

File: packages/dd-trace/src/sampler.js [hunk 1]
```diff
@@ -16,12 +16,15 @@ const SAMPLING_KNUTH_FACTOR = 1_111_111_111_111_111_111n
  * This class uses a deterministic sampling algorithm that is consistent across all languages.
  */
 class Sampler {
+  #threshold = BigInt(0)
```
Comment (watson) [inline packages/dd-trace/src/sampler.js]: Nit:

```suggestion
  #threshold = 0n
```

File: packages/dd-trace/src/sampler.js [hunk 2]
```diff
@@ -16,12 +16,15 @@ const SAMPLING_KNUTH_FACTOR = 1_111_111_111_111_111_111n
...
   /**
```
Comment (watson) [inline packages/dd-trace/src/sampler.js:21]: Nit:

```suggestion

  /**
```

File: packages/dd-trace/test/startup-log.spec.js [hunk 3]
```diff
@@ -5,10 +5,13 @@ require('./setup/tap')
 const os = require('os')
 const tracerVersion = require('../../../package.json').version
 const Config = require('../src/config')
+const SamplingRule = require('../src/sampling_rule')
+const assert = require('node:assert')
```
Comment (watson) [inline packages/dd-trace/test/startup-log.spec.js]: Nit: I like Node.js core modules to be at the top when possible (we should have a linting rule for that)

```suggestion
const assert = require('node:assert')
const tracerVersion = require('../../../package.json').version
const Config = require('../src/config')
const SamplingRule = require('../src/sampling_rule')
```

Comment (BridgeAR) [reply packages/dd-trace/test/startup-log.spec.js]: While I agree that it's easier to read it that way, I think we should just let a linter handle it with autofix at a later point.

**Review by watson — APPROVED** [review]
