### PR TITLE
fix stack overflow when cloning http res and overriding res.end

### LINKED ISSUE #927: Using koa2-connect causes application crash with "Maximum call stack size exceeded"
**Describe the bug**
When using koa2-connect or some library that does so, receiving a request that goes through that middleware will cause either an unhandled exception or an unhandled rejection, depending on the implementation.

I was able to create this small reproducible example:
```js
require('dd-trace').init()

const Koa = require('koa');
const app = new Koa();
const k2c = require('koa2-connect');

app.use(k2c(function (req, res, next) {
    res.end('ok')
}));

app.listen(3000, () => console.log(`Server listening`));
```

The issue can be triggered with: `curl http://localhost:3000`.

Dependency versions:
```
"dd-trace": "0.20.0",
"koa": "2.11.0",
"koa2-connect": "1.0.2"
```

**Environment**

* **Operation system:** Reproducing locally on Mac OS but also happens on 10.20.1-alpine docker image
* **Node version:** 10.20.1 and 12.16.2
* **Tracer version:** 0.20.0
* **Agent version:** Not relevant

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix stack overflow when cloning http `res` and overriding `res.end`.

### Motivation

We redefine the `res.end` property to be a setter and use a local variable within the wrapper to store the original function. When cloning `res`, both the clone and the original `res` object end up sharing the same local variable since they refer to the same setter. This means that when the clone tries to call the original by calling `res.end.apply(res, arguments)` it results in a stack overflow since it ends up calling itself.

By storing the original on the object itself instead, we can make sure that each clone has its own internal original function.

Fixes #927

### CODE REVIEW

File: packages/dd-trace/src/plugins/util/web.js [hunk 1]
```diff
@@ -64,8 +64,12 @@ const web = {
...
     analyticsSampler.sample(span, config.analytics, true)
 
-    wrapEnd(req)
-    wrapEvents(req)
+    if (!req._datadog.instrumented) {
+      wrapEnd(req)
+      wrapEvents(req)
+    }
+
+    req._datadog.instrumented = true
```
Comment (bengl) [inline packages/dd-trace/src/plugins/util/web.js:72]: Shouldn't this be inside the `if` block? I know it doesn't matter because it will always be set, but we only *need* to set it inside the block, right?

Comment (rochdev) [reply packages/dd-trace/src/plugins/util/web.js:72]: Correct. That's a small change, I'll do it now.

Comment (rochdev) [reply packages/dd-trace/src/plugins/util/web.js]: Done.
