### PR TITLE
Auto-instrument @opentelemetry/sdk-trace-node

### LINKED ISSUE #3240: Unmet peer warnings for @opentelemetry/api
**Expected behaviour**

There should be no warnings when installing `dd-trace` with `pnpm install`.

**Actual behaviour**

Getting warnings like:

```sh
my-package/my-folder
└─┬ dd-trace 3.23.0
  └─┬ @opentelemetry/core 1.3.1
    └── ✕ unmet peer @opentelemetry/api@">=1.0.0 <1.2.0": found 1.4.1 in dd-trace
```

It appears to be due to https://github.com/DataDog/dd-trace-js/pull/3233, `dd-trace` is declaring a dependency on `@opentelementry/core` 1.3.1 and `@opentelemetry/api` ^1.0.0, but that's pulling in 1.4.1 which is outside of the peer range in `@opentelemetry/core`.

This is happening for me with PNPM, it may also be happening with NPM or Yarn.

**Steps to reproduce**

Get the latest `dd-trace` and run `pnpm install` on your project.

**Environment**

* **Operation system:** Ubuntu 23.04
* **Node.js version:** 18.16.0
* **Tracer version:** 3.23.0
* **Agent version:** N/A
* **Relevant library versions:** PNPM 8.6.2

### PR DESCRIPTION
**Pull request by Qard**
### What does this PR do?

Auto-instrument `@opentelemetry/sdk-trace-node` when `DD_TRACE_OTEL_ENABLED` is set

### Motivation

We want to be able to enable our SDK with zero code changes.

Fixes #3240

### CODE REVIEW

File: packages/dd-trace/src/noop/proxy.js [hunk 1]
```diff
@@ -75,6 +75,10 @@ class Tracer {
     this.appsec.setUser(user)
     return this
   }
+
+  get TracerProvider () {
+    return require('../opentelemetry/tracer_provider')
+  }
```
Comment (Qard) [inline packages/dd-trace/src/noop/proxy.js:81]: Extra bug fix to allow accessing `TracerProvider` _before_ doing `tracer.init(...)`.

File: packages/dd-trace/src/opentelemetry/context_manager.js [hunk 2]
```diff
@@ -62,7 +62,7 @@ class ContextManager {
   bind (context, target) {
     const self = this
     return function (...args) {
-      return self.with(context, target, this, args)
+      return self.with(context, target, this, ...args)
```
Comment (Qard) [inline packages/dd-trace/src/opentelemetry/context_manager.js:65]: And another bug fix to ensure arguments are passed through bind properly.

**Review by bengl — APPROVED** [review]

**Review by bengl — APPROVED** [review]
