### PR TITLE
fix requests to the agent being traced

### LINKED ISSUE #1248: dd-trace reports its own activity as APM http traces
**Describe the bug**
Datadog is receiving extremely frequent traces like the attached screenshot, which are tracing the activity of dd-trace itself sending traces to the agent on localhost.

image

A workaround is manually adding the URL to the http blocklist solves the issue, like this
```
import tracer from 'dd-trace'
tracer.init()
tracer.use('http', {
  blocklist: ['http://localhost:8126/v0.4/traces']
})
export default tracer
```

**Environment**

Running in ECS Fargate with agent as a sidecar container.

"datadog/agent:latest"

Agent container definition (in Terraform HCL representation, not JSON)
```
  datadog_agent_container_definition = {
    name      = "datadog-agent"
    image     = "datadog/agent:latest"
    essential = true
    environment = [
      {
        name  = "DD_APM_ENABLED"
        value = "true"
      },
      {
        name  = "ECS_FARGATE"
        value = "true"
      }
    ]
    secrets = [
      {
        name      = "DD_API_KEY",
        valueFrom = data.aws_secretsmanager_secret.datadog_api_key.arn
      }
    ]
    # Expose port 8126 so that the dd-trace instrumentation in our app can deliver traces to
    # the Datadog agent
    portMappings = [
      {
        hostPort      = 8126
        protocol      = "tcp"
        containerPort = 8126
      },
    ]
    # Apply tight limits on how much CPU/memory can be used by the agent container.
    cpu    = 10
    memory = 256
    # Define these empty values to avoid unnecessary diffs (default is [], Terraform tries to set 'null')
    mountPoints = []
    volumesFrom = []
  }
```

App container definition:
```
base_container_definition = {
    name  = local.app_container_name
    image = var.image
    essential = true
    environment = [

      {
        name  = "DD_TRACE_AGENT_HOSTNAME"
        value = "localhost"
      },
      {
        name  = "DD_SERVICE"
        value = var.name
      }
    ]
    logConfiguration = {
      logDriver = "awsfirelens"
      options = {
        Name           = "datadog"
        apikey         = local.datadog_api_key
        Host           = "http-intake.logs.datadoghq.com"
        dd_service     = var.name
        dd_source      = "firelens"
        dd_message_key = "log"
        TLS            = "on",
        provider       = "ecs"
      }
    }
    # Define these empty values to avoid unnecessary diffs (default is [], Terraform tries to set 'null')
    cpu          = 0
    mountPoints  = []
    volumesFrom  = []
    portMappings = []
  }
```

* **Node version:**
14
* **Tracer version:**
```
$ yarn list dd-trace
yarn list v1.22.10
└─ dd-trace@0.31.0
```
* **Agent version:**
`:latest` tag

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix requests to the agent being traced.

### Motivation

Fix #1248

### CODE REVIEW

File: packages/dd-trace/test/plugins/agent.js [hunk 1]
```diff
@@ -22,7 +22,7 @@ module.exports = {
     agent = express()
     agent.use(bodyParser.raw({ limit: Infinity, type: 'application/msgpack' }))
     agent.use((req, res, next) => {
-      if (req.body.length === 0) return res.status(200).send()
+      if (!req.body.length) return res.status(200).send()
```
Comment (bengl) [inline packages/dd-trace/test/plugins/agent.js:25]: Why this change?

Comment (rochdev) [reply packages/dd-trace/test/plugins/agent.js:25]: `bodyParser` default to an empty object when the content type didn't match, which doesn't have a `length` property.

**Review by bengl — APPROVED** [review]
