### PR TITLE
esbuild: ensure aws-sdk can be built

### LINKED ISSUE #3479: 4.9.0 esbuild plugin causes [Cannot read properties of undefined (reading 'inherit')] on lambda init
Testing 4.9.0 in our build process specifically to test #3448 which I believe to be the cause of some of our previous instrumentation issues. I made no changes to code and simply installed dd-trace@4.9.0 in the build pipeline.  Build completed successfully but the deployed lambda function immediately fails during initialization phase with the following error:

```
INIT_START Runtime Version: nodejs:16.v16	Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:c1983f4e9ce3930d3093fa38128e12edac2324f4fe99adfb8e0d5fb6b6afadbc

TELEMETRY	Name: datadog-agent	State: Subscribed	Types: [Platform, Function, Extension]
2023-07-27T23:18:17.929Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read properties of undefined (reading 'inherit')",
    "stack": [
        "TypeError: Cannot read properties of undefined (reading 'inherit')",
        "    at /var/task/app.js:1:45662",
        "    at /var/task/app.js:1:227",
        "    at /var/task/app.js:16:811",
        "    at /var/task/app.js:1:227",
        "    at /var/task/app.js:16:1124",
        "    at /var/task/app.js:1:227",
        "    at /var/task/app.js:16:22349",
        "    at /var/task/app.js:1:227",
        "    at /var/task/app.js:16:27993",
        "    at /var/task/app.js:1:227"
    ]
}

2023-07-27T23:18:17.934Z	undefined	DEBUG	Inject into carrier: 
{
    "x-datadog-trace-id": "3697252533875077936",
    "x-datadog-parent-id": "3697252533875077936",
    "x-datadog-sampling-priority": "1"
}

```

Reverting the build pipeline to use dd-trace@4.8.1 resolves the error and returns us to the previous semi functional state we had before in which the dd supported integrations are not instrumented.

**Steps to reproduce**

1. build TypeScript project using dd-trace esbuild plugin on version 4.9.0 and the package.json and esbuild.config.js defined below
2. resulting lambda may fail in a similar way
3. revert to dd-trace@4.8.1
4. confirm functional lambda again

**Environment**

* **Operation system: ** Amazon Linux 2
* **Node.js version:** 16
* **Tracer version:** 
* Build time: 4.9.0   
* Runtime: lambda nodejs layer version 95 (dd-trace-js ^3.29.1)
* **Agent version:** Lambda Extension Layer 45 (Agent: 7.46.0)

Package json Dependencies:

```
  "dependencies": {
    "dotenv": "^16.0.3",
    "esbuild": "^0.18.2",
    "mongoose": "^7.3.0"
  },
  "devDependencies": {
    "@aws-lambda-powertools/logger": "^1.9.0",
    "@aws-lambda-powertools/metrics": "^1.9.0",
    "@aws-lambda-powertools/tracer": "^1.9.0",
    "@types/aws-lambda": "^8.10.117",
    "@types/jest": "^27.4.0",
    "@types/node": "^20.3.1",
    "@typescript-eslint/eslint-plugin": "^5.10.2",
    "@typescript-eslint/parser": "^5.10.2",
    "aws-lambda": "^1.0.7",
    "aws-sdk": "^2.1399.0",
    "esbuild-jest": "^0.5.0",
    "eslint": "^8.8.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^4.0.0",
    "jest": "^29.5.0",
    "prettier": "^2.5.1",
    "ts-jest": "^29.1.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.6"
  }

```

esbuild.config.js:

```
const ddPlugin = require('dd-trace/esbuild')
const { build } = require("esbuild");

console.log(`*************************** current directory: ${__dirname}`);
let dirN;

for (const x in process.argv) {
    const e = process.argv[x];
    console.log(e + " " + x);
    if (e == '--dir') {
        // get the dir value from the next argument
        const nextV = parseInt(x) + 1;
        dirN = process.argv[nextV];
    }
}

if (dirN == null) {
    dirN =  __dirname + "./.aws-sam/build/<function name redacted>/";
}

if (!dirN.endsWith("/")) {
    dirN = `${dirN}/`;
}

build({
    entryPoints: [`${__dirname}/src-ts/app.ts`],
    target: "node16",
    bundle: true,
    platform: "node",
    plugins: [ddPlugin],
    // external: ['graphql/language/visitor', 'graphql/language/printer', 'graphql/utilities', 'aws-sdk', 'datadog-lambda-js', 'dd-trace' ],
    sourcemap: true,
    minify: true,
    outfile: `${dirN}app.js`
}).catch((error) => {
    console.error(error);
    process.exit(1);
});

```

### PR DESCRIPTION
**Pull request by tlhunter**
### What does this PR do?
- adds an integration test for the aws-sdk library
- fixes #3479
- instead of inserting a "virtual" / "proxy" / intermediary file in the build using the `datadog` namespace to wrap a module
  - we now inject code into the existing module
  - this fixes a bug where
    - file A is instrumented
    - file A exports a subset of all the things it's going to export
    - file A requires file B
    - file B requires file A and uses an "early" export
    - file B fails as it receives an empty export object instead of the early, partially exported object

### Motivation
- aws-sdk currently fails to build with the dd-trace esbuild plugin

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### CODE REVIEW

File: packages/datadog-esbuild/index.js [hunk 1]
```diff
@@ -109,46 +110,48 @@ module.exports.setup = function (build) {
...
-    const path = data.raw !== data.pkg
+    const pkgPath = data.raw !== data.pkg
       ? `${data.pkg}/${data.path}`
       : data.pkg
 
+    // Read the content of the module file of interest
+    const fileCode = fs.readFileSync(args.path, 'utf8')
+
     const contents = `
+      // Module code from ${args.path}
```
Comment (tlhunter) [inline packages/datadog-esbuild/index.js:143]: Can we remove this comment? I think it would be superfluous with the existing path string esbuild uses as a method name

**Review by Qard — APPROVED** [review]

File: packages/datadog-esbuild/index.js [hunk 2]
```diff
@@ -109,46 +110,48 @@ module.exports.setup = function (build) {
...
+      (function() {
+        ${fileCode}
+      })(...arguments);
```
Comment (tlhunter) [inline packages/datadog-esbuild/index.js:146]: For future reviewers: This is for a weird case where a user can access `arguments` from the root of a commonJS file, which contains `[exports, require, module, __filename, __dirname]`. Surely nobody would use `arguments` directly but we've certainly seen weirder things happen.

File: packages/datadog-esbuild/index.js [hunk 3]
```diff
@@ -109,46 +110,48 @@ module.exports.setup = function (build) {
...
       const dc = require('diagnostics_channel');
```
Comment (tlhunter) [inline packages/datadog-esbuild/index.js:147]: I'm starting to wonder if there's any weird things that could happen with these variables being in a scope that the application code can access. Maybe to be safe we should wrap them in curlys:

```js
(function() {
  ${fileCode}
})(...arguments);
{
  const ch = dc.foo
  ...
  module.exports = foo
}
```

Comment (tlhunter) [reply packages/datadog-esbuild/index.js:146]: The fear is that someone could have code in the file like "console.log(payload)" which could introduce a subtle breaking change.

**Comment by tlhunter** [comment]
I suspect we may have an issue when a third party module begins with a `#!` shebang.

**Comment by tlhunter** [comment]
Actually, the shebang shouldn't really matter for modules. It's beneficial for application code but surely it's super rare that a module would use it. I won't block the PR for it.

**Review by Qard — APPROVED** [review]

File: package.json [hunk 4]
```diff
@@ -103,6 +103,7 @@
   "devDependencies": {
     "@types/node": ">=16",
     "autocannon": "^4.5.2",
+    "aws-sdk": "^2.1446.0",
```
Comment (rochdev) [inline package.json:106]: Any way to not need this? Can't we use what gets installed in the `versions` folder somehow? If we start depending on all our integrations this will become way too bloated.
