### PR TITLE
esbuild: early bailout when loading app local modules

### LINKED ISSUE #3547: `dd-trace/esbuild` doesn't resolve Typescript and aliased imports
**Expected behaviour**
Typescript projects bundled by esbuild with `dd-trace/esbuild` plugin enabled should build without any warnings when importing `.ts`/`.tsx` files or using [`compilerOptions.baseUrl` TS option](https://www.typescriptlang.org/tsconfig#baseUrl) for shorter import paths

**Actual behaviour**
Getting `MISSING: Unable to find "{imported path}". Is the package dead code?` warnings build build

**Steps to reproduce**
Example repo: https://github.com/zemlanin/dd-trace-esbuild-ts

Examples of problematic imports:

```ts
 // importing `./module/index.ts`
import * from "./module";
import * from "./module/index.ts";

// importing `src/module/index.js` with `compilerOptions.baseUrl: "src"` in `tsconfig`
import * from "module";
```

**Environment**

* **Operation system:** macOS Ventura 13.4
* **Node.js version:** 18.16.0
* **Tracer version:** `dd-trace@4.12.0`
* **Agent version:** n/a
* **Relevant library versions:** `esbuild@0.17.16` and higher

```json
{
  "dependencies": {
    "dd-trace": "^4.12.0",
    "esbuild": "^0.19.2"
  }
}

```

### PR DESCRIPTION
**Pull request by tlhunter**
### What does this PR do?
- bail out of the esbuild bundling process early if the currently considered file is local to the application
- we only need to bundling if we're requiring a package from the outside or if we're in a package requiring from the inside
- also treats filenames beginning with `@` as local filenames, a common convention with Next.js (and Vue?)

### Motivation
- should fix #3547

### Plugin Checklist

- [ ] Unit tests.
- [ ] TypeScript [definitions][1].
- [ ] TypeScript [tests][2].
- [ ] API [documentation][3].
- [ ] CircleCI [jobs/workflows][4].
- [ ] Plugin is [exported][5].

[1]: https://github.com/DataDog/dd-trace-js/blob/master/index.d.ts
[2]: https://github.com/DataDog/dd-trace-js/blob/master/docs/test.ts
[3]: https://github.com/DataDog/documentation/blob/master/content/en/tracing/trace_collection/library_config/nodejs.md
[4]: https://github.com/DataDog/dd-trace-js/blob/master/.circleci/config.yml
[5]: https://github.com/DataDog/dd-trace-js/blob/master/packages/dd-trace/src/plugins/index.js

### CODE REVIEW

File: integration-tests/esbuild/build-and-test-typescript.mjs [hunk 1]
```diff
@@ -0,0 +1,26 @@
+#!/usr/bin/env node
```
Comment (tlhunter) [inline integration-tests/esbuild/build-and-test-typescript.mjs:1]: This config file is largely unchanged from one provided by a user.

**Review by bengl — APPROVED** [review]

**Comment by tlhunter** [comment]
The parametric test keeps failing:

```
______ Test_Partial_Flushing.test_partial_flushing_disabled[library_env0] ______
[gw0] linux -- Python 3.9.17 /home/runner/work/dd-trace-js/dd-trace-js/venv/bin/python

self = <tests.parametric.test_partial_flushing.Test_Partial_Flushing object at 0x7f19335[26](https://github.com/DataDog/dd-trace-js/actions/runs/5907433032/job/16026173211#step:5:27)d90>
test_agent = <tests.parametric.conftest._TestAgentAPI object at 0x7f193311[28](https://github.com/DataDog/dd-trace-js/actions/runs/5907433032/job/16026173211#step:5:29)b0>
test_library = <utils.parametric._library_client.APMLibrary object at 0x7f19333f3ee0>

    @pytest.mark.parametrize(
        "library_env", [{"DD_TRACE_PARTIAL_FLUSH_MIN_SPANS": "1", "DD_TRACE_PARTIAL_FLUSH_ENABLED": "false",}]
    )
    @missing_feature(context.library == "cpp", reason="partial flushing not implemented")
    @missing_feature(context.library == "java", reason="does not use DD_TRACE_PARTIAL_FLUSH_ENABLED")
    @missing_feature(context.library == "ruby", reason="no way to configure partial flushing")
    @missing_feature(context.library == "php", reason="partial flushing not implemented")
    def test_partial_flushing_disabled(self, test_agent, test_library):
        """
            Create a trace with a root span and a single child. Finish the child, and ensure
            partial flushing does NOT trigger, since it's explicitly disabled.
        """
>       no_partial_flush_test(self, test_agent, test_library)

tests/parametric/test_partial_flushing.py:66: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <tests.parametric.test_partial_flushing.Test_Partial_Flushing object at 0x7f1933526d90>
test_agent = <tests.parametric.conftest._TestAgentAPI object at 0x7f19331128b0>
test_library = <utils.parametric._library_client.APMLibrary object at 0x7f19333f3ee0>

    def no_partial_flush_test(self, test_agent, test_library):
        """
            Create a trace with a root span and one child. Finish the child, and ensure
            partial flushing does NOT trigger.
        """
        with test_library:
            with test_library.start_span(name="root") as parent_span:
                with test_library.start_span(name="child1", parent_id=parent_span.span_id):
                    pass
                try:
                    partial_traces = test_agent.wait_for_num_traces(1, clear=True)
>                   assert partial_traces is None
E                   AssertionError: assert [[{'duration': 4135986, 'error': 0, 'meta': {'language': 'javascript', 'runtime-id': '6b598ce4-1412-4[30](https://github.com/DataDog/dd-trace-js/actions/runs/5907433032/job/16026173211#step:5:31)f-b76d-5c704cf51025', 'version': '1.0.0'}, 'metrics': {'_sampling_priority_v1': 1.0, 'process_id': 1.0}, ...}]] is None

tests/parametric/test_partial_flushing.py:99: AssertionError
```
