### PR TITLE
fix support for q v2

### LINKED ISSUE #1803: Error instrumenting `q` module
**Describe the bug**

I'm seeing the following error with modules:

+ twilio@3.71.3 => q@2.0.3
+ dd-trace@2.0.0

```json
{
  "error": {
    "errorClass": "Error",
    "stacktrace": [
      {
        "columnNumber": 11,
        "method": "assertMethod",
        "file": "node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js",
        "lineNumber": 116
      },
      {
        "columnNumber": 3,
        "method": "wrapMethod",
        "file": "node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js",
        "lineNumber": 35
      },
      {
        "columnNumber": 7,
        "method": "Object.wrap",
        "file": "node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js",
        "lineNumber": 65
      },
      {
        "columnNumber": 11,
        "method": "<anonymous>",
        "file": "node_modules/dd-trace/packages/datadog-instrumentations/src/q.js",
        "lineNumber": 11
      },
      {
        "columnNumber": 12,
        "method": "loaderHook",
        "file": "node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/instrument.js",
        "lineNumber": 30
      },
      {
        "columnNumber": 36,
        "method": "Module.Hook._require.Module.require",
        "file": "node_modules/dd-trace/packages/dd-trace/src/ritm.js",
        "lineNumber": 104
      },
      {
        "columnNumber": 39,
        "method": "Module.Hook._require.Module.require",
        "file": "node_modules/dd-trace/packages/dd-trace/src/ritm.js",
        "lineNumber": 66
      },
      {
        "columnNumber": 39,
        "method": "Module.Hook._require.Module.require",
        "file": "node_modules/dd-trace/packages/dd-trace/src/ritm.js",
        "lineNumber": 66
      },
      {
        "columnNumber": 9,
        "method": "Object.<anonymous>",
        "file": "node_modules/twilio/lib/base/RequestClient.js",
        "lineNumber": 7
      },
      {
        "columnNumber": 39,
        "method": "Module.Hook._require.Module.require",
        "file": "node_modules/dd-trace/packages/dd-trace/src/ritm.js",
        "lineNumber": 66
      }
    ],
    "message": "No original method then.",
    "name": "Error"
  }
}
```

This error did not occur with `dd-trace@1.6.0`.

**Environment**

* **Operation system:** Debian Buster
* **Node version:** 14
* **Tracer version:** 2.0.0
* **Agent version:**

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix support for q v2. I also fixed the tests since they were always passing even if promise libraries were not patched properly.

### Motivation

Version 2 of `q` is in beta so it was not tested by our test suite and it was actually not supported.

Fixes #1803

### CODE REVIEW

File: packages/datadog-instrumentations/test/helpers/promise.js [hunk 1]
```diff
@@ -13,54 +13,59 @@ module.exports = (name, factory, versionRange) => {
...
         })
 
         it('should run the then() callbacks in the context where then() was called', () => {
-          const store = storage.getStore()
+          const store = 'store'
 
           let promise = new Promise((resolve, reject) => {
             setImmediate(() => {
-              storage.run(store, () => {
+              storage.run('promise', () => {
```
Comment (bengl) [inline packages/datadog-instrumentations/test/helpers/promise.js:26]: If this is here, do we still need the surrounding setImmediate?

**Review by bengl — CHANGES_REQUESTED** [review]

File: packages/datadog-instrumentations/test/helpers/promise.js (hunk 1 above)
Comment (rochdev) [reply packages/datadog-instrumentations/test/helpers/promise.js:26]: I think it's better to make it asynchronous yes. There have been issues in the past where the scope would leak synchronously, which can result in unexpected results. By making it asynchronous, it would leak in a different scope.

**Review by bengl — APPROVED** [review]
