### PR TITLE
fix mongoose v7 tests and restore support

### LINKED ISSUE #2872: Mongoose v7 Support
Seems like mongoose v7 is not yet supported (causing errors and I see a TODO comment about it). Creating this issue to track it, but happy to close if its tracked somewhere else

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix mongoose v7 tests and restore support.

### Motivation

Fix regression introduced in #2851 causing removal of Mongoose support for the latest version.

Fixes #2872

### CODE REVIEW

File: packages/datadog-instrumentations/src/mongoose.js [hunk 1]
```diff
@@ -19,7 +19,7 @@ function wrapAddQueue (addQueue) {
 
 addHook({
   name: 'mongoose',
-  versions: ['>=4.6.4 <7'] // TODO: Mongoose v7 compat
+  versions: ['>=4.6.4 <5', '5', '6', '>=7']
```
Comment (Qard) [inline packages/datadog-instrumentations/src/mongoose.js:22]: Why break out `5` and `6` like this? Couldn't the `<5` just be extended? And why the `>=7`? This could all be reduced to a single `>=4.6.4`, if I understand correctly?

**Review by Qard — APPROVED** [review]
LGTM, though not clear why the versions range is the way it is. 🤔

File: packages/datadog-instrumentations/src/mongoose.js (hunk 1 above)
Comment (rochdev) [reply packages/datadog-instrumentations/src/mongoose.js:22]: This was just a quick and easy way to add tests for those versions. I can add them to `externals.json` if you prefer this to be out of `src`.

Comment (Qard) [reply packages/datadog-instrumentations/src/mongoose.js:22]: I don't see any test changes related to that. Did you forget to `git add` something?

Comment (rochdev) [reply packages/datadog-instrumentations/src/mongoose.js:22]: Not sure I understand, there were definitely multiple test changes that I see in GitHub 🤔
