### PR TITLE
fix restify disconnected trace when middleware breaks async context

### LINKED ISSUE #2248: dd-trace 2.12 breaks restify traces
**Expected behaviour**
Full tracing of service calls for services with restify once upgraded to dd-trace 2.12

**Actual behaviour**
Only seeing initial entry point in trace. 

**Steps to reproduce**
Upgrade restify service using dd-trace from v2.11 to v2.12.

Call endpoint.

Compare traces. 

**Environment**

* **Operation system:**
* debian 16-bullseye-slim
* **Node.js version:**
* 16.16.0
* **Tracer version:**
 v2.12.1
* **Agent version:**
*
* **Relevant library versions:**
restify 8.6.1
opentracing 0.14.7

initialization
```
// server.ts
// datadog first
import './datadog';
...rest of code
```
```
// datadog.ts
import ddtrace from 'dd-trace';
const tracer = ddtrace.init();

tracer.use('restify', { headers: ['correlation-id', 'user-agent'] });
tracer.use('http', {
    splitByDomain: true,
});
tracer.use('aws-sdk', {
    splitByAwsService: true,
});

import { initGlobalTracer } from 'opentracing';
initGlobalTracer(tracer);
export { tracer };

```

Example trace with 2.11
Screen Shot 2022-08-02 at 11 36 03 AM
Same endpoint, only change is upgrading to 2.12.1
Screen Shot 2022-08-02 at 11 36 46 AM

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix restify disconnected trace when middleware breaks async context.

### Motivation

Fixes #2248

### Additional Notes

Regression from #2196

### CODE REVIEW

File: packages/datadog-instrumentations/src/restify.js [hunk 1]
```diff
@@ -37,18 +40,37 @@ function wrapFn (fn) {
...
+    }
+  }
+}
+
+function wrapNext (req, next) {
+  return function () {
+    nextChannel.publish({ req })
+    exitChannel.publish({ req })
+
+    next.apply(null, arguments)
```
Comment (uurien) [inline packages/datadog-instrumentations/src/restify.js:66]: why are we forcing it to `null` instead of use `this`?

Comment (rochdev) [reply packages/datadog-instrumentations/src/restify.js:66]: It was a copy paste from another file that did the same. I don't know why so I'll change it.

**Review by Qard — APPROVED** [review]
