### PR TITLE
fix mixing esm and commonjs modules and add error handling

### LINKED ISSUE #1932: bunyan patching fails with Error: No target object provided.
**Describe the bug**
During loading, an error is returned:

```
/Users/admin/project/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:108
    throw new Error('No target object provided.')
          ^

Error: No target object provided.
    at assertMethod (/Users/admin/project/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:108:11)
    at wrapMethod (/Users/admin/project/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:35:3)
    at Object.wrap (/Users/admin/project/node_modules/dd-trace/packages/datadog-shimmer/src/shimmer.js:65:7)
    at /Users/admin/project/node_modules/dd-trace/packages/datadog-instrumentations/src/bunyan.js:11:11
    at cjsPostLoad (/Users/admin/project/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/instrument.js:84:5)
    at addHook (/Users/admin/project/node_modules/dd-trace/packages/datadog-instrumentations/src/helpers/instrument.js:33:3)
    at Object.<anonymous> (/Users/admin/project/node_modules/dd-trace/packages/datadog-instrumentations/src/bunyan.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
```

**Environment**

* **Operation system:**
* * MacOs Monterey & node:14-alpine docker container
* **Node version:**
* * v14.19.0
* **Tracer version:**
* * "^2.4.0"
* **Agent version:**
* * 7

**Index.js**
```
import tracer from 'dd-trace';
tracer.init({service: 'myservice', plugins: true, logInjection: true});
import bunyan from 'bunyan';

const logger = bunyan.createLogger({
  name: 'myservice-logger',
  stream: process.stdout,
})
```

**package.json**
```
  "name": "myservice",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module"
  "dependencies": {
    "bunyan": "^1.8.15",
    "dd-trace": "^2.4.0"
  },
...
```

### PR DESCRIPTION
**Pull request by rochdev**
### What does this PR do?

Fix ESM support when mixed with CommonJS. I also added error handling in the new plugin system hooks so that errors don't result in unhandled exceptions and instead log the error, similar to the legacy instrumenter.

### Motivation

When mixing import-in-the-middle and require-in-the-middle together, the module structure received by the hook would be different where a CommonJS would get its default export moved to a `default` property when going through import-in-the-middle. Since we only instrument a known small subset of modules, it's safe to assume that instrumenting only the `default` property is enough for import-in-the-middle.

Using both systems together was also resulting in double-patching which is now fixed as well. Unfortunately the fix didn't really play well with the post-load hook for CommonJS, so I removed it completely. It wasn't useful anyway since we load instrumentations when dd-trace is imported and not when it's initialized.

Fixes #1932

### CODE REVIEW

File: packages/datadog-instrumentations/src/helpers/hook.js [hunk 1]
```diff
@@ -0,0 +1,41 @@
...
+    if (this._patched[filename]) return moduleExports
+
+    this._patched[filename] = true
+
+    return onrequire(moduleExports, moduleName, moduleBaseDir)
+  }
+
+  this._ritmHook = ritm(modules, {}, safeHook)
+  this._iitmHook = iitm(modules, {}, (moduleExports, moduleName, moduleBaseDir) => {
+    // Default export is always moved to `default` for CommonJS modules.
```
Comment (bengl) [inline packages/datadog-instrumentations/src/helpers/hook.js:25]: Let's add a TODO comment to implement this in IITM

File: packages/datadog-instrumentations/src/helpers/hook.js [hunk 2]
```diff
@@ -0,0 +1,41 @@
+'use strict'
+
+const path = require('path')
+const iitm = require('../../../dd-trace/src/iitm')
+const ritm = require('../../../dd-trace/src/ritm')
+
+function Hook (modules, onrequire) {
+  if (!(this instanceof Hook)) return new Hook(modules, onrequire)
```
Comment (bengl) [inline packages/datadog-instrumentations/src/helpers/hook.js:8]: This function is never actually called with `new`. If we assume that, then we can do away with this line and make all the properties on `this` into local variables.

**Review by bengl — CHANGES_REQUESTED** [review]
My main concern at this point is that this creates a disparity between the behaviour of the old plugin system versus the new one. I'd be less worried about this since we're aiming to remove the old plugin system, but the new plugin system has existed for over 3 months now and we're still only about 60% done converting the plugins. This makes me thing it will stick around even longer, so we might need to deal with this difference in behaviour before the plugins are all converted.

I know patching post-load isn't documented or supported, but it is a behaviour that the tracer does today, so we need to address it somehow other than (nearly) silently dropping support for just 60% of plugins.

File: packages/datadog-instrumentations/src/helpers/hook.js [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+    this._patched[filename] = true
+
+    return onrequire(moduleExports, moduleName, moduleBaseDir)
+  }
+
+  this._ritmHook = ritm(modules, {}, safeHook)
+  this._iitmHook = iitm(modules, {}, (moduleExports, moduleName, moduleBaseDir) => {
+    // Default export is always moved to `default` for CommonJS modules.
+    if (moduleExports && moduleExports.default) {
+      moduleExports.default = safeHook(moduleExports.default, moduleName, moduleBaseDir)
```
Comment (bmeck) [inline packages/datadog-instrumentations/src/helpers/hook.js:27]: I'm not quite sure I understand what is going on here. Any ESM module with a default export would go through this?

File: packages/datadog-instrumentations/src/helpers/hook.js [hunk 4]
```diff
@@ -0,0 +1,41 @@
+'use strict'
+
+const path = require('path')
+const iitm = require('../../../dd-trace/src/iitm')
+const ritm = require('../../../dd-trace/src/ritm')
+
+function Hook (modules, onrequire) {
+  if (!(this instanceof Hook)) return new Hook(modules, onrequire)
+
+  this._patched = {}
```
Comment (bmeck) [inline packages/datadog-instrumentations/src/helpers/hook.js:10]: can we just preemptively go to Object.create(null) here if we use it as a dictionary

File: packages/datadog-instrumentations/src/helpers/hook.js (hunk 1 above)
Comment (rochdev) [reply packages/datadog-instrumentations/src/helpers/hook.js:25]: This rule only applies to us specifically, not sure it should go in iitm unless the goal of iitm changes to only support CommonJS modules loaded through ESM loader hooks.

File: packages/datadog-instrumentations/src/helpers/hook.js (hunk 2 above)
Comment (rochdev) [reply packages/datadog-instrumentations/src/helpers/hook.js:8]: So just a function that returns a plain object with `unhook` on it?

File: packages/datadog-instrumentations/src/helpers/hook.js (hunk 4 above)
Comment (rochdev) [reply packages/datadog-instrumentations/src/helpers/hook.js:10]: I've seen cases where object literals are faster than objects created with `Object.create` when not iterated on. However, in this case it would only affect start time so the trade-off is probably worth it.

**Comment by rochdev** [comment]
> I know patching post-load isn't documented or supported, but it is a behaviour that the tracer does today, so we need to address it somehow other than (nearly) silently dropping support for just 60% of plugins.

The new plugin system patches when `dd-trace` is imported, not when it's initialized, which means it's equivalent. It's also worth noting that all this ever caused is bugs anyway.

File: packages/datadog-instrumentations/src/helpers/hook.js (hunk 4 above)
Comment (bmeck) [reply packages/datadog-instrumentations/src/helpers/hook.js]: seems fine either way

File: packages/datadog-instrumentations/src/helpers/hook.js (hunk 3 above)
Comment (bmeck) [reply packages/datadog-instrumentations/src/helpers/hook.js:27]: sure, maybe just a note so there is a breadcrumb if things do upgrade

Comment (rochdev) [reply packages/datadog-instrumentations/src/helpers/hook.js:27]: There is already a comment about this. What should be clarified?

Also, can we detect if a module is CommonJS vs ESM from the loader hook? This would allow handling this more cleanly and in a forward compatible way.

File: packages/datadog-instrumentations/src/helpers/hook.js (hunk 2 above)
Comment (bengl) [reply packages/datadog-instrumentations/src/helpers/hook.js:8]: I forgot that we sill need unhook. Disregard for now.

File: packages/datadog-instrumentations/src/helpers/hook.js (hunk 3 above)
Comment (bengl) [reply packages/datadog-instrumentations/src/helpers/hook.js:27]: @rochdev if you just add "which are the only type of modules instrumented by dd-trace-js right now." or something like that, then that should be sufficient explanation for now I think.

File: packages/datadog-instrumentations/src/helpers/hook.js (hunk 1 above)
Comment (bengl) [reply packages/datadog-instrumentations/src/helpers/hook.js:25]: [It can, yeah.](https://github.com/DataDog/dd-trace-js/pull/1934#discussion_r836702221) Right now we're not dependent on that, but we do something there if needed.

**Comment by bengl** [comment]
> The new plugin system patches when dd-trace is imported, not when it's initialized, which means it's equivalent.

That's only true/relevant in cases where dd-trace _is_ actually imported first, which we can't necessarily count on, so it's not equivalent.

> It's also worth noting that all this ever caused is bugs anyway.

That's not true. It case caused functionality that is not a bug to occur. It's true that depending on this functionality often results in bugs though, so that's certainly worth considering.

**Review by bengl — DISMISSED** [review]

**Review by bengl — APPROVED** [review]
